# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 21:47:49 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    5000152, 4999077, 26, 0, 28, 
    0, 34, 0, 61, 0, 
    61, 0, 54, 0, 93, 
    65, 73, 90, 87, 99, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 253,
    'CO_f + *_f -> CO_f + *_f(<-)': 254,
    'CO_g + *_f -> CO_f(->)': 5000152,
    'CO_g + *_f -> CO_f(<-)': 4999077,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 88,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 176,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 253,
    'CO_f + *_f -> CO_f + *_f(<-)': 254,
    'CO_g + *_f -> CO_f(->)': 5000152,
    'CO_g + *_f -> CO_f(<-)': 4999077,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 88,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 176,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00288930243973,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00290072260748,
    'CO_g + *_f -> CO_f(->)': 57.1025745954,
    'CO_g + *_f -> CO_f(<-)': 57.0902979151,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00100497476165,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00200994952329,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

