# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 19:48:50 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    5000247, 4999242, 19, 0, 23, 
    0, 11, 0, 36, 0, 
    36, 0, 34, 0, 44, 
    49, 63, 74, 54, 68, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 161,
    'CO_f + *_f -> CO_f + *_f(<-)': 191,
    'CO_g + *_f -> CO_f(->)': 5000247,
    'CO_g + *_f -> CO_f(<-)': 4999242,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 53,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 106,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 161,
    'CO_f + *_f -> CO_f + *_f(<-)': 191,
    'CO_g + *_f -> CO_f(->)': 5000247,
    'CO_g + *_f -> CO_f(<-)': 4999242,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 53,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 106,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00183925220317,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00218197000501,
    'CO_g + *_f -> CO_f(->)': 57.1224553489,
    'CO_g + *_f -> CO_f(<-)': 57.1109743025,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.000605468116573,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00121093623315,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

