# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Wed Jan 23 20:17:26 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    6923, 5883, 6999, 5884, 85, 
    0, 93, 0, 41, 0, 
    53, 0, 37, 0, 50, 
    0, 41, 0, 50, 0, 
    42, 0, 42, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 
]

reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 356,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 13922,
    'CO_g + *_b -> CO_b(<-)': 11767,
    'O2_g + 2*_b -> 2O_b(->)': 178,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 356,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 13922,
    'CO_g + *_b -> CO_b(<-)': 11767,
    'O2_g + 2*_b -> 2O_b(->)': 178,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0,
}

reaction_rates = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 1.97770212542e-07,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0.0,
    'CO_g + *_b -> CO_b(->)': 7.73414859272e-06,
    'CO_g + *_b -> CO_b(<-)': 6.53697216567e-06,
    'O2_g + 2*_b -> 2O_b(->)': 9.88851062709e-08,
    'O2_g + 2*_b -> 2O_b(<-)': 0.0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0.0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0.0,
}

