# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Fri Jan  4 14:25:12 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    2807, 2803, 47624, 46715, 5, 
    0, 7, 0, 4, 0, 
    1, 0, 2, 0, 3, 
    0, 4, 0, 5, 0, 
    3, 0, 9, 0, 1, 
    0, 7, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 
]

reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 47624,
    'CO_g + *_f -> CO_f(<-)': 46715,
    'CO_g + *_h -> CO_h(->)': 2807,
    'CO_g + *_h -> CO_h(<-)': 2803,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 16,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 6,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0,
    'O_f + *_h -> O_h + *_f(->)': 0,
    'O_f + *_h -> O_h + *_f(<-)': 0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 17,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 12,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 47624,
    'CO_g + *_f -> CO_f(<-)': 46715,
    'CO_g + *_h -> CO_h(->)': 2807,
    'CO_g + *_h -> CO_h(<-)': 2803,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 16,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 6,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0,
    'O_f + *_h -> O_h + *_f(->)': 0,
    'O_f + *_h -> O_h + *_f(<-)': 0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 17,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 12,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0,
}

reaction_rates = {
    'CO_g + *_f -> CO_f(->)': 55.3782491191,
    'CO_g + *_f -> CO_f(<-)': 54.3212436502,
    'CO_g + *_h -> CO_h(->)': 3.26404219044,
    'CO_g + *_h -> CO_h(<-)': 3.25939090124,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0186051567677,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 0.00697693378789,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0.0,
    'O_f + *_h -> O_h + *_f(->)': 0.0,
    'O_f + *_h -> O_h + *_f(<-)': 0.0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 0.0197679790657,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0.0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 0.0139538675758,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0.0,
}

