# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 19:48:50 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    5000231, 4999228, 14, 0, 20, 
    0, 18, 0, 37, 0, 
    34, 0, 33, 0, 56, 
    51, 63, 64, 78, 73, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 197,
    'CO_f + *_f -> CO_f + *_f(<-)': 188,
    'CO_g + *_f -> CO_f(->)': 5000231,
    'CO_g + *_f -> CO_f(<-)': 4999228,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 52,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 104,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 197,
    'CO_f + *_f -> CO_f + *_f(<-)': 188,
    'CO_g + *_f -> CO_f(->)': 5000231,
    'CO_g + *_f -> CO_f(<-)': 4999228,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 52,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 104,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00225031540795,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00214750912028,
    'CO_g + *_f -> CO_f(->)': 57.1172429574,
    'CO_g + *_f -> CO_f(<-)': 57.1057857678,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.000593991884332,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00118798376866,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

