# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 23:29:30 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14992907, 14981041, 1831, 0, 1802, 
    0, 1851, 0, 3712, 0, 
    3516, 0, 3740, 0, 1575, 
    1656, 1620, 1640, 1534, 1575, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4729,
    'CO_f + *_f -> CO_f + *_f(<-)': 4871,
    'CO_g + *_f -> CO_f(->)': 14992907,
    'CO_g + *_f -> CO_f(<-)': 14981041,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 5484,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 10968,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4729,
    'CO_f + *_f -> CO_f + *_f(<-)': 4871,
    'CO_g + *_f -> CO_f(->)': 14992907,
    'CO_g + *_f -> CO_f(<-)': 14981041,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 5484,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 10968,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0179751497576,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0185148983864,
    'CO_g + *_f -> CO_f(->)': 56.9887394008,
    'CO_g + *_f -> CO_f(<-)': 56.9436361809,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0208449400022,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0416898800044,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

