# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 19:48:50 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    5000187, 4999120, 28, 0, 29, 
    0, 27, 0, 59, 0, 
    55, 0, 54, 0, 71, 
    62, 65, 82, 73, 88, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 209,
    'CO_f + *_f -> CO_f + *_f(<-)': 232,
    'CO_g + *_f -> CO_f(->)': 5000187,
    'CO_g + *_f -> CO_f(<-)': 4999120,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 84,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 168,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 209,
    'CO_f + *_f -> CO_f + *_f(<-)': 232,
    'CO_g + *_f -> CO_f(->)': 5000187,
    'CO_g + *_f -> CO_f(<-)': 4999120,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 84,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 168,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00238698704755,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00264966983269,
    'CO_g + *_f -> CO_f(->)': 57.107089016,
    'CO_g + *_f -> CO_f(<-)': 57.094902819,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.000959363215285,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00191872643057,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

