# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Wed Jan 23 15:03:09 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
steps = []
coverages = [[], [], [], [], [], [], []]

possible_types = [
    'O_u', 'O_d', 'O_l', 'O_r', 'V', 
    'O_s', 'C', 
]


# -------------------- flush 0 ---------------------
times_0 = [
    0.0, 1.39224896561e-07, 94121.9718727, 234349.478154, 380287.420752, 
]

times.extend(times_0)

steps_0 = [
    0, 6666, 13332, 19998, 26664, 
]

steps.extend(steps_0)

coverages_0 = [
    (0.0, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 0.0, 0.0),
    (1.0, 0.5361111111111112, 0.0, 0.0, 0.0),
    (0.0, 0.0044444444444444444, 0.0, 0.0, 0.0),
    (0.0, 0.45944444444444443, 1.0, 1.0, 1.0),
]

coverages[0].extend(coverages_0[0])
coverages[1].extend(coverages_0[1])
coverages[2].extend(coverages_0[2])
coverages[3].extend(coverages_0[3])
coverages[4].extend(coverages_0[4])
coverages[5].extend(coverages_0[5])
coverages[6].extend(coverages_0[6])
