# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 23:29:30 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14993590, 14984434, 1397, 0, 1397, 
    0, 1335, 0, 2768, 0, 
    2744, 0, 2746, 0, 1598, 
    1604, 1651, 1611, 1548, 1577, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4797,
    'CO_f + *_f -> CO_f + *_f(<-)': 4792,
    'CO_g + *_f -> CO_f(->)': 14993590,
    'CO_g + *_f -> CO_f(<-)': 14984434,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 4129,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 8258,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4797,
    'CO_f + *_f -> CO_f + *_f(<-)': 4792,
    'CO_g + *_f -> CO_f(->)': 14993590,
    'CO_g + *_f -> CO_f(<-)': 14984434,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 4129,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 8258,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0182296016107,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0182106005667,
    'CO_g + *_f -> CO_f(->)': 56.9787726526,
    'CO_g + *_f -> CO_f(<-)': 56.9439779409,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0156910621327,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0313821242655,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

