# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 00:23:55 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    4998449, 4993891, 617, 0, 616, 
    0, 598, 0, 1188, 0, 
    1263, 0, 1211, 0, 368, 
    365, 372, 348, 336, 378, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 1076,
    'CO_f + *_f -> CO_f + *_f(<-)': 1091,
    'CO_g + *_f -> CO_f(->)': 4998449,
    'CO_g + *_f -> CO_f(<-)': 4993891,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 1831,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 3662,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 1076,
    'CO_f + *_f -> CO_f + *_f(<-)': 1091,
    'CO_g + *_f -> CO_f(->)': 4998449,
    'CO_g + *_f -> CO_f(<-)': 4993891,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 1831,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 3662,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0122866205473,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0124579024322,
    'CO_g + *_f -> CO_f(->)': 57.0762511039,
    'CO_g + *_f -> CO_f(<-)': 57.0242042485,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0209078087565,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0418156175131,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

