# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 19:48:50 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    5000207, 4999160, 27, 0, 20, 
    0, 27, 0, 56, 0, 
    42, 0, 50, 0, 65, 
    48, 75, 74, 71, 78, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 211,
    'CO_f + *_f -> CO_f + *_f(<-)': 200,
    'CO_g + *_f -> CO_f(->)': 5000207,
    'CO_g + *_f -> CO_f(<-)': 4999160,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 74,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 148,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 211,
    'CO_f + *_f -> CO_f + *_f(<-)': 200,
    'CO_g + *_f -> CO_f(->)': 5000207,
    'CO_g + *_f -> CO_f(<-)': 4999160,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 74,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 148,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00241058342075,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00228491319502,
    'CO_g + *_f -> CO_f(->)': 57.1251947607,
    'CO_g + *_f -> CO_f(<-)': 57.1132332401,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.000845417882157,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00169083576431,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

