# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Wed Jan 23 15:11:21 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    8818, 5963, 8782, 5910, 969, 
    0, 995, 0, 534, 0, 
    568, 0, 468, 0, 472, 
    0, 491, 0, 480, 0, 
    459, 0, 456, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 
]

reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 3928,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 17600,
    'CO_g + *_b -> CO_b(<-)': 11873,
    'O2_g + 2*_b -> 2O_b(->)': 1964,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 3928,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 17600,
    'CO_g + *_b -> CO_b(<-)': 11873,
    'O2_g + 2*_b -> 2O_b(->)': 1964,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0,
}

reaction_rates = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 2.18220970838e-06,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0.0,
    'CO_g + *_b -> CO_b(->)': 9.7777217076e-06,
    'CO_g + *_b -> CO_b(<-)': 6.59607328604e-06,
    'O2_g + 2*_b -> 2O_b(->)': 1.09110485419e-06,
    'O2_g + 2*_b -> 2O_b(<-)': 0.0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0.0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0.0,
}

