# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Fri Jan  4 14:31:31 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    2251, 2222, 48192, 47313, 2, 
    0, 1, 0, 3, 0, 
    1, 0, 2, 0, 0, 
    0, 1, 0, 0, 0, 
    5, 0, 1, 0, 3, 
    0, 3, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 
]

reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 48192,
    'CO_g + *_f -> CO_f(<-)': 47313,
    'CO_g + *_h -> CO_h(->)': 2251,
    'CO_g + *_h -> CO_h(<-)': 2222,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 6,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 3,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0,
    'O_f + *_h -> O_h + *_f(->)': 0,
    'O_f + *_h -> O_h + *_f(<-)': 0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 7,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 6,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 48192,
    'CO_g + *_f -> CO_f(<-)': 47313,
    'CO_g + *_h -> CO_h(->)': 2251,
    'CO_g + *_h -> CO_h(<-)': 2222,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 6,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 3,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0,
    'O_f + *_h -> O_h + *_f(->)': 0,
    'O_f + *_h -> O_h + *_f(<-)': 0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 7,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 6,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0,
}

reaction_rates = {
    'CO_g + *_f -> CO_f(->)': 56.3631026324,
    'CO_g + *_f -> CO_f(<-)': 55.3350654641,
    'CO_g + *_h -> CO_h(->)': 2.63266401115,
    'CO_g + *_h -> CO_h(<-)': 2.59874697147,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00701731855483,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 0.00350865927741,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0.0,
    'O_f + *_h -> O_h + *_f(->)': 0.0,
    'O_f + *_h -> O_h + *_f(<-)': 0.0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 0.0081868716473,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0.0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 0.00701731855483,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0.0,
}

