# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 21:47:50 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    4999888, 4998451, 88, 0, 93, 
    0, 89, 0, 183, 0, 
    176, 0, 181, 0, 128, 
    155, 132, 122, 145, 169, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 405,
    'CO_f + *_f -> CO_f + *_f(<-)': 446,
    'CO_g + *_f -> CO_f(->)': 4999888,
    'CO_g + *_f -> CO_f(<-)': 4998451,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 270,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 540,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 405,
    'CO_f + *_f -> CO_f + *_f(<-)': 446,
    'CO_g + *_f -> CO_f(->)': 4999888,
    'CO_g + *_f -> CO_f(<-)': 4998451,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 270,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 540,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00462477025606,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00509295687457,
    'CO_g + *_f -> CO_f(->)': 57.0946501383,
    'CO_g + *_f -> CO_f(<-)': 57.0782407683,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00308318017071,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00616636034141,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

