# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 00:23:19 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    4996876, 4988001, 1295, 0, 1360, 
    0, 1335, 0, 2735, 0, 
    2527, 0, 2718, 0, 488, 
    551, 516, 547, 502, 549, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 1506,
    'CO_f + *_f -> CO_f + *_f(<-)': 1647,
    'CO_g + *_f -> CO_f(->)': 4996876,
    'CO_g + *_f -> CO_f(<-)': 4988001,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 3990,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 7980,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 1506,
    'CO_f + *_f -> CO_f + *_f(<-)': 1647,
    'CO_g + *_f -> CO_f(->)': 4996876,
    'CO_g + *_f -> CO_f(<-)': 4988001,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 3990,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 7980,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0171935506314,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0188033053718,
    'CO_g + *_f -> CO_f(->)': 57.0478356605,
    'CO_g + *_f -> CO_f(<-)': 56.9465124455,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0455526341429,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0911052682858,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

