# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 18:23:14 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14991712, 14974948, 2656, 0, 2687, 
    0, 2590, 0, 5465, 0, 
    5173, 0, 5228, 0, 1545, 
    1628, 1651, 1603, 1529, 1585, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4725,
    'CO_f + *_f -> CO_f + *_f(<-)': 4816,
    'CO_g + *_f -> CO_f(->)': 14991712,
    'CO_g + *_f -> CO_f(<-)': 14974948,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 7933,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 15866,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4725,
    'CO_f + *_f -> CO_f + *_f(<-)': 4816,
    'CO_g + *_f -> CO_f(->)': 14991712,
    'CO_g + *_f -> CO_f(<-)': 14974948,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 7933,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 15866,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0179686565029,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0183147195171,
    'CO_g + *_f -> CO_f(->)': 57.0118356231,
    'CO_g + *_f -> CO_f(<-)': 56.9480839707,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0301683284736,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0603366569472,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

