# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 19:48:50 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    5000236, 4999219, 20, 0, 18, 
    0, 21, 0, 42, 0, 
    40, 0, 36, 0, 45, 
    47, 70, 68, 68, 70, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 183,
    'CO_f + *_f -> CO_f + *_f(<-)': 185,
    'CO_g + *_f -> CO_f(->)': 5000236,
    'CO_g + *_f -> CO_f(<-)': 4999219,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 59,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 118,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 183,
    'CO_f + *_f -> CO_f + *_f(<-)': 185,
    'CO_g + *_f -> CO_f(->)': 5000236,
    'CO_g + *_f -> CO_f(<-)': 4999219,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 59,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 118,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00209045297862,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00211329945926,
    'CO_g + *_f -> CO_f(->)': 57.1188974863,
    'CO_g + *_f -> CO_f(<-)': 57.1072800509,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.000673971178899,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0013479423578,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

