# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 18:23:14 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14992286, 14977831, 2231, 0, 2283, 
    0, 2264, 0, 4550, 0, 
    4470, 0, 4536, 0, 1539, 
    1645, 1634, 1612, 1555, 1564, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4728,
    'CO_f + *_f -> CO_f + *_f(<-)': 4821,
    'CO_g + *_f -> CO_f(->)': 14992286,
    'CO_g + *_f -> CO_f(<-)': 14977831,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 6778,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 13556,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4728,
    'CO_f + *_f -> CO_f + *_f(<-)': 4821,
    'CO_g + *_f -> CO_f(->)': 14992286,
    'CO_g + *_f -> CO_f(<-)': 14977831,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 6778,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 13556,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0179749331109,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0183285009576,
    'CO_g + *_f -> CO_f(->)': 56.9977449301,
    'CO_g + *_f -> CO_f(<-)': 56.9427898416,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.025768632958,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0515372659161,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

