# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 18:23:14 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14989720, 14964962, 3937, 0, 3943, 
    0, 4050, 0, 8133, 0, 
    7573, 0, 8154, 0, 1549, 
    1618, 1607, 1635, 1550, 1569, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4706,
    'CO_f + *_f -> CO_f + *_f(<-)': 4822,
    'CO_g + *_f -> CO_f(->)': 14989720,
    'CO_g + *_f -> CO_f(<-)': 14964962,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 11930,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 23860,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4706,
    'CO_f + *_f -> CO_f + *_f(<-)': 4822,
    'CO_g + *_f -> CO_f(->)': 14989720,
    'CO_g + *_f -> CO_f(<-)': 14964962,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 11930,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 23860,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0179048647351,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0183462086173,
    'CO_g + *_f -> CO_f(->)': 57.0312173858,
    'CO_g + *_f -> CO_f(<-)': 56.9370209045,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0453899354633,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0907798709265,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

