# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 18:23:14 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14992006, 14976427, 2419, 0, 2387, 
    0, 2534, 0, 4997, 0, 
    4736, 0, 4947, 0, 1575, 
    1582, 1666, 1593, 1556, 1575, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4797,
    'CO_f + *_f -> CO_f + *_f(<-)': 4750,
    'CO_g + *_f -> CO_f(->)': 14992006,
    'CO_g + *_f -> CO_f(<-)': 14976427,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 7340,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 14680,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4797,
    'CO_f + *_f -> CO_f + *_f(<-)': 4750,
    'CO_g + *_f -> CO_f(->)': 14992006,
    'CO_g + *_f -> CO_f(<-)': 14976427,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 7340,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 14680,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0182397352718,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0180610261707,
    'CO_g + *_f -> CO_f(->)': 57.0044237301,
    'CO_g + *_f -> CO_f(<-)': 56.9451873665,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0279090383354,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0558180766708,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

