# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 18:23:14 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14990361, 14968224, 3556, 0, 3477, 
    0, 3586, 0, 7167, 0, 
    6871, 0, 7200, 0, 1554, 
    1619, 1660, 1603, 1535, 1587, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4749,
    'CO_f + *_f -> CO_f + *_f(<-)': 4809,
    'CO_g + *_f -> CO_f(->)': 14990361,
    'CO_g + *_f -> CO_f(<-)': 14968224,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 10619,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 21238,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4749,
    'CO_f + *_f -> CO_f + *_f(<-)': 4809,
    'CO_g + *_f -> CO_f(->)': 14990361,
    'CO_g + *_f -> CO_f(<-)': 14968224,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 10619,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 21238,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.018067109815,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0182953739946,
    'CO_g + *_f -> CO_f(->)': 57.0293742585,
    'CO_g + *_f -> CO_f(<-)': 56.9451561894,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0403989553855,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0807979107709,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

