# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 23:29:30 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14995079, 14991852, 387, 0, 394, 
    0, 383, 0, 784, 0, 
    765, 0, 779, 0, 1573, 
    1614, 1658, 1613, 1550, 1569, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4781,
    'CO_f + *_f -> CO_f + *_f(<-)': 4796,
    'CO_g + *_f -> CO_f(->)': 14995079,
    'CO_g + *_f -> CO_f(<-)': 14991852,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 1164,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 2328,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4781,
    'CO_f + *_f -> CO_f + *_f(<-)': 4796,
    'CO_g + *_f -> CO_f(->)': 14995079,
    'CO_g + *_f -> CO_f(<-)': 14991852,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 1164,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 2328,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0181581577345,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0182151274827,
    'CO_g + *_f -> CO_f(->)': 56.9510582981,
    'CO_g + *_f -> CO_f(<-)': 56.9388022062,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00442085245826,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00884170491652,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

