# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Fri Jan  4 21:14:08 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    3082146, 3080903, 59, 0, 54, 
    0, 59, 0, 128, 0, 
    106, 0, 110, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 
]

reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 3082146,
    'CO_g + *_f -> CO_f(<-)': 3080903,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 172,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 344,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 3082146,
    'CO_g + *_f -> CO_f(<-)': 3080903,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 172,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 344,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_g + *_f -> CO_f(->)': 57.0767527622,
    'CO_g + *_f -> CO_f(<-)': 57.0537342538,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00318518378918,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00637036757837,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

