# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Wed Jan 23 15:11:22 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    200162, 0, 199793, 0, 100263, 
    0, 99882, 0, 57906, 0, 
    57975, 0, 48577, 0, 47283, 
    0, 47661, 0, 46941, 0, 
    46652, 0, 46905, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 
]

reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 399900,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 399955,
    'CO_g + *_b -> CO_b(<-)': 0,
    'O2_g + 2*_b -> 2O_b(->)': 200145,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 399900,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 399955,
    'CO_g + *_b -> CO_b(<-)': 0,
    'O2_g + 2*_b -> 2O_b(->)': 200145,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0,
}

reaction_rates = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 3423291.5687,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0.0,
    'CO_g + *_b -> CO_b(->)': 3423762.38899,
    'CO_g + *_b -> CO_b(<-)': 0.0,
    'O2_g + 2*_b -> 2O_b(->)': 1713315.05631,
    'O2_g + 2*_b -> 2O_b(<-)': 0.0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0.0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0.0,
}

