# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 23:29:30 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14993905, 14985903, 1155, 0, 1201, 
    0, 1196, 0, 2425, 0, 
    2300, 0, 2379, 0, 1573, 
    1580, 1631, 1630, 1547, 1575, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4751,
    'CO_f + *_f -> CO_f + *_f(<-)': 4785,
    'CO_g + *_f -> CO_f(->)': 14993905,
    'CO_g + *_f -> CO_f(<-)': 14985903,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 3552,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 7104,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4751,
    'CO_f + *_f -> CO_f + *_f(<-)': 4785,
    'CO_g + *_f -> CO_f(->)': 14993905,
    'CO_g + *_f -> CO_f(<-)': 14985903,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 3552,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 7104,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0180514464243,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0181806295812,
    'CO_g + *_f -> CO_f(->)': 56.9694112396,
    'CO_g + *_f -> CO_f(<-)': 56.9390076036,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0134958403913,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0269916807827,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

