# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 23:29:30 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14992665, 14979773, 2033, 0, 2012, 
    0, 1952, 0, 4001, 0, 
    3878, 0, 4115, 0, 1579, 
    1632, 1632, 1608, 1547, 1573, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4758,
    'CO_f + *_f -> CO_f + *_f(<-)': 4813,
    'CO_g + *_f -> CO_f(->)': 14992665,
    'CO_g + *_f -> CO_f(<-)': 14979773,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 5997,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 11994,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4758,
    'CO_f + *_f -> CO_f + *_f(<-)': 4813,
    'CO_g + *_f -> CO_f(->)': 14992665,
    'CO_g + *_f -> CO_f(<-)': 14979773,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 5997,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 11994,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0180860858333,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0182951515586,
    'CO_g + *_f -> CO_f(->)': 56.9900433082,
    'CO_g + *_f -> CO_f(<-)': 56.9410383022,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0227957664444,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0455915328888,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

