# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 23:29:30 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14994175, 14987304, 1031, 0, 1013, 
    0, 942, 0, 1902, 0, 
    1979, 0, 2091, 0, 1540, 
    1615, 1639, 1634, 1566, 1569, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4745,
    'CO_f + *_f -> CO_f + *_f(<-)': 4818,
    'CO_g + *_f -> CO_f(->)': 14994175,
    'CO_g + *_f -> CO_f(<-)': 14987304,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 2986,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 5972,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4745,
    'CO_f + *_f -> CO_f + *_f(<-)': 4818,
    'CO_g + *_f -> CO_f(->)': 14994175,
    'CO_g + *_f -> CO_f(<-)': 14987304,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 2986,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 5972,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0180278932448,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0183052454485,
    'CO_g + *_f -> CO_f(->)': 56.9680476699,
    'CO_g + *_f -> CO_f(<-)': 56.9419423686,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0113448449376,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0226896898752,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

