# This file was automatically generated by scaks (https://github.com/PytLab/scaks).
# Version 0.1.0
# Date: Sun Jun 30 17:38:21 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    165, 0, 12, 0, 9, 
    0, 14, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 
]

reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 165,
    'CO_g + *_f -> CO_f(<-)': 0,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 35,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 165,
    'CO_g + *_f -> CO_f(<-)': 0,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 35,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_g + *_f -> CO_f(->)': 14320.53535505437,
    'CO_g + *_f -> CO_f(<-)': 0.0,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 3037.6893177388056,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

