# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 19:48:51 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    5000262, 4999265, 17, 0, 21, 
    0, 11, 0, 35, 0, 
    34, 0, 29, 0, 37, 
    51, 47, 68, 61, 62, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 145,
    'CO_f + *_f -> CO_f + *_f(<-)': 181,
    'CO_g + *_f -> CO_f(->)': 5000262,
    'CO_g + *_f -> CO_f(<-)': 4999265,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 49,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 98,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 145,
    'CO_f + *_f -> CO_f + *_f(<-)': 181,
    'CO_g + *_f -> CO_f(->)': 5000262,
    'CO_g + *_f -> CO_f(<-)': 4999265,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 49,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 98,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00165631021113,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00206753205665,
    'CO_g + *_f -> CO_f(->)': 57.1171379925,
    'CO_g + *_f -> CO_f(<-)': 57.1057494319,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.000559718623071,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00111943724614,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

