# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 18:23:14 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14990064, 14966782, 3861, 0, 3694, 
    0, 3637, 0, 7461, 0, 
    7500, 0, 7423, 0, 1582, 
    1610, 1642, 1624, 1551, 1569, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4775,
    'CO_f + *_f -> CO_f + *_f(<-)': 4803,
    'CO_g + *_f -> CO_f(->)': 14990064,
    'CO_g + *_f -> CO_f(<-)': 14966782,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 11192,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 22384,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4775,
    'CO_f + *_f -> CO_f + *_f(<-)': 4803,
    'CO_g + *_f -> CO_f(->)': 14990064,
    'CO_g + *_f -> CO_f(<-)': 14966782,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 11192,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 22384,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0181678985439,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0182744328181,
    'CO_g + *_f -> CO_f(->)': 57.0341281504,
    'CO_g + *_f -> CO_f(<-)': 56.9455449014,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0425832713095,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.085166542619,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

