# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Wed Jan 23 20:09:14 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    200077, 0, 199736, 0, 100332, 
    0, 100053, 0, 51290, 0, 
    51474, 0, 49647, 0, 49260, 
    0, 49264, 0, 49594, 0, 
    49628, 0, 49644, 0, 0, 
    0, 0, 1, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 
]

reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 399801,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 399813,
    'CO_g + *_b -> CO_b(<-)': 0,
    'O2_g + 2*_b -> 2O_b(->)': 200385,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 1,
}

steady_reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 399801,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 399813,
    'CO_g + *_b -> CO_b(<-)': 0,
    'O2_g + 2*_b -> 2O_b(->)': 200385,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 1,
}

reaction_rates = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 1875048.58555,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0.0,
    'CO_g + *_b -> CO_b(->)': 1875104.86501,
    'CO_g + *_b -> CO_b(<-)': 0.0,
    'O2_g + 2*_b -> 2O_b(->)': 939796.575835,
    'O2_g + 2*_b -> 2O_b(<-)': 0.0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0.0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 4.68995471635,
}

