# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 23:29:30 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14995351, 14993296, 210, 0, 183, 
    0, 185, 0, 406, 0, 
    367, 0, 383, 0, 1620, 
    1630, 1621, 1630, 1543, 1575, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4784,
    'CO_f + *_f -> CO_f + *_f(<-)': 4835,
    'CO_g + *_f -> CO_f(->)': 14995351,
    'CO_g + *_f -> CO_f(<-)': 14993296,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 578,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 1156,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4784,
    'CO_f + *_f -> CO_f + *_f(<-)': 4835,
    'CO_g + *_f -> CO_f(->)': 14995351,
    'CO_g + *_f -> CO_f(<-)': 14993296,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 578,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 1156,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0181682731685,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0183619566827,
    'CO_g + *_f -> CO_f(->)': 56.9480838683,
    'CO_g + *_f -> CO_f(<-)': 56.940279562,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0021950798268,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0043901596536,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

