# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 18:23:14 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14990901, 14970957, 3159, 0, 3135, 
    0, 3229, 0, 6503, 0, 
    6172, 0, 6371, 0, 1589, 
    1621, 1607, 1629, 1548, 1579, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4744,
    'CO_f + *_f -> CO_f + *_f(<-)': 4829,
    'CO_g + *_f -> CO_f(->)': 14990901,
    'CO_g + *_f -> CO_f(<-)': 14970957,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 9523,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 19046,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4744,
    'CO_f + *_f -> CO_f + *_f(<-)': 4829,
    'CO_g + *_f -> CO_f(->)': 14990901,
    'CO_g + *_f -> CO_f(<-)': 14970957,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 9523,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 19046,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.018043817372,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0183671151116,
    'CO_g + *_f -> CO_f(->)': 57.0179342087,
    'CO_g + *_f -> CO_f(<-)': 56.9420771485,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0362207573427,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0724415146854,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

