# This file was automatically generated by scaks (https://github.com/PytLab/scaks).
# Version 0.1.0
# Date: Wed Jan 23 13:40:12 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []

coverages = []


# -------------------- flush 0 ---------------------
times_0 = [
    0.019999999999999934, 
]

times.extend(times_0)

coverages_0 = [
    [9.815574469329892e-08, 0.09039038051914092],
]

coverages.extend(coverages_0)


# -------------------- flush 1 ---------------------
times_1 = [
    0.04000000000000012, 
]

times.extend(times_1)

coverages_1 = [
    [5.489658371377314e-08, 0.15087391827270702],
]

coverages.extend(coverages_1)


# -------------------- flush 2 ---------------------
times_2 = [
    0.06000000000000069, 
]

times.extend(times_2)

coverages_2 = [
    [4.0745105955980934e-08, 0.19315202628492267],
]

coverages.extend(coverages_2)


# -------------------- flush 3 ---------------------
times_3 = [
    0.08000000000000126, 
]

times.extend(times_3)

coverages_3 = [
    [3.386557713235758e-08, 0.223614381795306],
]

coverages.extend(coverages_3)


# -------------------- flush 4 ---------------------
times_4 = [
    0.10000000000000184, 
]

times.extend(times_4)

coverages_4 = [
    [2.988899857853067e-08, 0.24604583454529547],
]

coverages.extend(coverages_4)


# -------------------- flush 5 ---------------------
times_5 = [
    0.12000000000000241, 
]

times.extend(times_5)

coverages_5 = [
    [2.735748578771192e-08, 0.2628298137546132],
]

coverages.extend(coverages_5)


# -------------------- flush 6 ---------------------
times_6 = [
    0.1400000000000009, 
]

times.extend(times_6)

coverages_6 = [
    [2.564583008307775e-08, 0.2755386048427166],
]

coverages.extend(coverages_6)


# -------------------- flush 7 ---------------------
times_7 = [
    0.1599999999999987, 
]

times.extend(times_7)

coverages_7 = [
    [2.4440731640991462e-08, 0.28524881123516505],
]

coverages.extend(coverages_7)


# -------------------- flush 8 ---------------------
times_8 = [
    0.1799999999999965, 
]

times.extend(times_8)

coverages_8 = [
    [2.3567973042224177e-08, 0.2927192461019176],
]

coverages.extend(coverages_8)


# -------------------- flush 9 ---------------------
times_9 = [
    0.1999999999999943, 
]

times.extend(times_9)

coverages_9 = [
    [2.2922751162738177e-08, 0.2984969860519729],
]

coverages.extend(coverages_9)


# -------------------- flush 10 ---------------------
times_10 = [
    0.2199999999999921, 
]

times.extend(times_10)

coverages_10 = [
    [2.243896291103642e-08, 0.30298384663210465],
]

coverages.extend(coverages_10)


# -------------------- flush 11 ---------------------
times_11 = [
    0.2399999999999899, 
]

times.extend(times_11)

coverages_11 = [
    [2.207196153917247e-08, 0.3064793645562991],
]

coverages.extend(coverages_11)


# -------------------- flush 12 ---------------------
times_12 = [
    0.2599999999999877, 
]

times.extend(times_12)

coverages_12 = [
    [2.179098954944345e-08, 0.30920919381443124],
]

coverages.extend(coverages_12)


# -------------------- flush 13 ---------------------
times_13 = [
    0.2799999999999855, 
]

times.extend(times_13)

coverages_13 = [
    [2.1574515543486664e-08, 0.3113457390070938],
]

coverages.extend(coverages_13)


# -------------------- flush 14 ---------------------
times_14 = [
    0.2999999999999833, 
]

times.extend(times_14)

coverages_14 = [
    [2.1406934599636434e-08, 0.3130201134563791],
]

coverages.extend(coverages_14)


# -------------------- flush 15 ---------------------
times_15 = [
    0.3199999999999811, 
]

times.extend(times_15)

coverages_15 = [
    [2.1276712485941915e-08, 0.31433368972377773],
]

coverages.extend(coverages_15)


# -------------------- flush 16 ---------------------
times_16 = [
    0.3399999999999789, 
]

times.extend(times_16)

coverages_16 = [
    [2.1175197877069972e-08, 0.3153653218879763],
]

coverages.extend(coverages_16)


# -------------------- flush 17 ---------------------
times_17 = [
    0.35999999999997667, 
]

times.extend(times_17)

coverages_17 = [
    [2.109586485797867e-08, 0.31617608155884747],
]

coverages.extend(coverages_17)


# -------------------- flush 18 ---------------------
times_18 = [
    0.37999999999997447, 
]

times.extend(times_18)

coverages_18 = [
    [2.1033832408473173e-08, 0.31681366156800955],
]

coverages.extend(coverages_18)


# -------------------- flush 19 ---------------------
times_19 = [
    0.39999999999997227, 
]

times.extend(times_19)

coverages_19 = [
    [2.0985148397337957e-08, 0.3173152385686449],
]

coverages.extend(coverages_19)


# -------------------- flush 20 ---------------------
times_20 = [
    0.41999999999997006, 
]

times.extend(times_20)

coverages_20 = [
    [2.0946955490757335e-08, 0.31770996671526225],
]

coverages.extend(coverages_20)


# -------------------- flush 21 ---------------------
times_21 = [
    0.43999999999996786, 
]

times.extend(times_21)

coverages_21 = [
    [2.0916959516130756e-08, 0.31802067777359067],
]

coverages.extend(coverages_21)


# -------------------- flush 22 ---------------------
times_22 = [
    0.45999999999996566, 
]

times.extend(times_22)

coverages_22 = [
    [2.089339351645354e-08, 0.318265258918937],
]

coverages.extend(coverages_22)


# -------------------- flush 23 ---------------------
times_23 = [
    0.47999999999996346, 
]

times.extend(times_23)

coverages_23 = [
    [2.0874835655088165e-08, 0.3184578114942728],
]

coverages.extend(coverages_23)


# -------------------- flush 24 ---------------------
times_24 = [
    0.49999999999996125, 
]

times.extend(times_24)

coverages_24 = [
    [2.086032674223607e-08, 0.3186094994818915],
]

coverages.extend(coverages_24)


# -------------------- flush 25 ---------------------
times_25 = [
    0.519999999999959, 
]

times.extend(times_25)

coverages_25 = [
    [2.0848699909729406e-08, 0.318729034160631],
]

coverages.extend(coverages_25)


# -------------------- flush 26 ---------------------
times_26 = [
    0.5399999999999568, 
]

times.extend(times_26)

coverages_26 = [
    [2.0840108890500085e-08, 0.3188232033292238],
]

coverages.extend(coverages_26)


# -------------------- flush 27 ---------------------
times_27 = [
    0.5599999999999546, 
]

times.extend(times_27)

coverages_27 = [
    [2.0832467822462924e-08, 0.3188973796923686],
]

coverages.extend(coverages_27)


# -------------------- flush 28 ---------------------
times_28 = [
    0.5799999999999524, 
]

times.extend(times_28)

coverages_28 = [
    [2.0827144343028774e-08, 0.3189558237255894],
]

coverages.extend(coverages_28)


# -------------------- flush 29 ---------------------
times_29 = [
    0.5999999999999502, 
]

times.extend(times_29)

coverages_29 = [
    [2.0822616775010487e-08, 0.31900188022792964],
]

coverages.extend(coverages_29)


# -------------------- flush 30 ---------------------
times_30 = [
    0.619999999999948, 
]

times.extend(times_30)

coverages_30 = [
    [2.081910038869347e-08, 0.3190381706354605],
]

coverages.extend(coverages_30)


# -------------------- flush 31 ---------------------
times_31 = [
    0.6399999999999458, 
]

times.extend(times_31)

coverages_31 = [
    [2.081652681119931e-08, 0.3190667602587487],
]

coverages.extend(coverages_31)


# -------------------- flush 32 ---------------------
times_32 = [
    0.6599999999999436, 
]

times.extend(times_32)

coverages_32 = [
    [2.0814223837353424e-08, 0.31908928895036265],
]

coverages.extend(coverages_32)


# -------------------- flush 33 ---------------------
times_33 = [
    0.6799999999999414, 
]

times.extend(times_33)

coverages_33 = [
    [2.081255555986197e-08, 0.31910705039730775],
]

coverages.extend(coverages_33)


# -------------------- flush 34 ---------------------
times_34 = [
    0.6999999999999392, 
]

times.extend(times_34)

coverages_34 = [
    [2.0811202025770082e-08, 0.3191210535742121],
]

coverages.extend(coverages_34)


# -------------------- flush 35 ---------------------
times_35 = [
    0.719999999999937, 
]

times.extend(times_35)

coverages_35 = [
    [2.0810146761714097e-08, 0.31913208884168054],
]

coverages.extend(coverages_35)


# -------------------- flush 36 ---------------------
times_36 = [
    0.7399999999999348, 
]

times.extend(times_36)

coverages_36 = [
    [2.0809313463457785e-08, 0.31914078922920547],
]

coverages.extend(coverages_36)


# -------------------- flush 37 ---------------------
times_37 = [
    0.7599999999999326, 
]

times.extend(times_37)

coverages_37 = [
    [2.080865602848229e-08, 0.31914765433988734],
]

coverages.extend(coverages_37)


# -------------------- flush 38 ---------------------
times_38 = [
    0.7799999999999304, 
]

times.extend(times_38)

coverages_38 = [
    [2.0808137177903955e-08, 0.3191530723998192],
]

coverages.extend(coverages_38)


# -------------------- flush 39 ---------------------
times_39 = [
    0.7999999999999282, 
]

times.extend(times_39)

coverages_39 = [
    [2.0807729105675605e-08, 0.3191573338460841],
]

coverages.extend(coverages_39)


# -------------------- flush 40 ---------------------
times_40 = [
    0.819999999999926, 
]

times.extend(times_40)

coverages_40 = [
    [2.080740707780502e-08, 0.31916069680740433],
]

coverages.extend(coverages_40)


# -------------------- flush 41 ---------------------
times_41 = [
    0.8399999999999238, 
]

times.extend(times_41)

coverages_41 = [
    [2.0807154413485415e-08, 0.31916333549168435],
]

coverages.extend(coverages_41)


# -------------------- flush 42 ---------------------
times_42 = [
    0.8599999999999216, 
]

times.extend(times_42)

coverages_42 = [
    [2.0806955929815728e-08, 0.31916540835828106],
]

coverages.extend(coverages_42)


# -------------------- flush 43 ---------------------
times_43 = [
    0.8799999999999194, 
]

times.extend(times_43)

coverages_43 = [
    [2.080679955729193e-08, 0.3191670414549006],
]

coverages.extend(coverages_43)


# -------------------- flush 44 ---------------------
times_44 = [
    0.8999999999999172, 
]

times.extend(times_44)

coverages_44 = [
    [2.0806676456086358e-08, 0.3191683270916092],
]

coverages.extend(coverages_44)


# -------------------- flush 45 ---------------------
times_45 = [
    0.919999999999915, 
]

times.extend(times_45)

coverages_45 = [
    [2.0806578558032224e-08, 0.3191693495181051],
]

coverages.extend(coverages_45)


# -------------------- flush 46 ---------------------
times_46 = [
    0.9399999999999128, 
]

times.extend(times_46)

coverages_46 = [
    [2.0806502075663034e-08, 0.31917014830319573],
]

coverages.extend(coverages_46)


# -------------------- flush 47 ---------------------
times_47 = [
    0.9599999999999106, 
]

times.extend(times_47)

coverages_47 = [
    [2.0806440543840428e-08, 0.31917079093423467],
]

coverages.extend(coverages_47)


# -------------------- flush 48 ---------------------
times_48 = [
    0.9799999999999084, 
]

times.extend(times_48)

coverages_48 = [
    [2.0806393037944294e-08, 0.31917128708103887],
]

coverages.extend(coverages_48)


# -------------------- flush 49 ---------------------
times_49 = [
    0.9999999999999062, 
]

times.extend(times_49)

coverages_49 = [
    [2.080635517708381e-08, 0.31917168249482847],
]

coverages.extend(coverages_49)


# -------------------- flush 50 ---------------------
times_50 = [
    1.019999999999904, 
]

times.extend(times_50)

coverages_50 = [
    [2.0806325809403137e-08, 0.31917198921049544],
]

coverages.extend(coverages_50)


# -------------------- flush 51 ---------------------
times_51 = [
    1.039999999999902, 
]

times.extend(times_51)

coverages_51 = [
    [2.0806303235562015e-08, 0.31917222497448794],
]

coverages.extend(coverages_51)


# -------------------- flush 52 ---------------------
times_52 = [
    1.0599999999998997, 
]

times.extend(times_52)

coverages_52 = [
    [2.080628550473072e-08, 0.3191724101560003],
]

coverages.extend(coverages_52)


# -------------------- flush 53 ---------------------
times_53 = [
    1.0799999999998975, 
]

times.extend(times_53)

coverages_53 = [
    [2.080627205991703e-08, 0.3191725505743818],
]

coverages.extend(coverages_53)


# -------------------- flush 54 ---------------------
times_54 = [
    1.0999999999998953, 
]

times.extend(times_54)

coverages_54 = [
    [2.0806261469832614e-08, 0.3191726611781431],
]

coverages.extend(coverages_54)


# -------------------- flush 55 ---------------------
times_55 = [
    1.119999999999893, 
]

times.extend(times_55)

coverages_55 = [
    [2.080625333997844e-08, 0.31917274608723273],
]

coverages.extend(coverages_55)


# -------------------- flush 56 ---------------------
times_56 = [
    1.1399999999998909, 
]

times.extend(times_56)

coverages_56 = [
    [2.0806246506126717e-08, 0.31917281746055587],
]

coverages.extend(coverages_56)


# -------------------- flush 57 ---------------------
times_57 = [
    1.1599999999998887, 
]

times.extend(times_57)

coverages_57 = [
    [2.080624100785466e-08, 0.31917287488497575],
]

coverages.extend(coverages_57)


# -------------------- flush 58 ---------------------
times_58 = [
    1.1799999999998865, 
]

times.extend(times_58)

coverages_58 = [
    [2.0806236812378686e-08, 0.31917291870306297],
]

coverages.extend(coverages_58)


# -------------------- flush 59 ---------------------
times_59 = [
    1.1999999999998843, 
]

times.extend(times_59)

coverages_59 = [
    [2.080623348991011e-08, 0.3191729534034075],
]

coverages.extend(coverages_59)


# -------------------- flush 60 ---------------------
times_60 = [
    1.219999999999882, 
]

times.extend(times_60)

coverages_60 = [
    [2.0806230344601456e-08, 0.3191729862530979],
]

coverages.extend(coverages_60)


# -------------------- flush 61 ---------------------
times_61 = [
    1.2399999999998799, 
]

times.extend(times_61)

coverages_61 = [
    [2.0806227931256448e-08, 0.31917301145815546],
]

coverages.extend(coverages_61)


# -------------------- flush 62 ---------------------
times_62 = [
    1.2599999999998777, 
]

times.extend(times_62)

coverages_62 = [
    [2.0806226521167716e-08, 0.3191730261853606],
]

coverages.extend(coverages_62)


# -------------------- flush 63 ---------------------
times_63 = [
    1.2799999999998755, 
]

times.extend(times_63)

coverages_63 = [
    [2.080622512934214e-08, 0.319173040721641],
]

coverages.extend(coverages_63)


# -------------------- flush 64 ---------------------
times_64 = [
    1.2999999999998733, 
]

times.extend(times_64)

coverages_64 = [
    [2.080622397921212e-08, 0.3191730527335809],
]

coverages.extend(coverages_64)


# -------------------- flush 65 ---------------------
times_65 = [
    1.319999999999871, 
]

times.extend(times_65)

coverages_65 = [
    [2.0806223323536492e-08, 0.31917305958147574],
]

coverages.extend(coverages_65)


# -------------------- flush 66 ---------------------
times_66 = [
    1.3399999999998689, 
]

times.extend(times_66)

coverages_66 = [
    [2.080622316917155e-08, 0.31917306119373945],
]

coverages.extend(coverages_66)


# -------------------- flush 67 ---------------------
times_67 = [
    1.3599999999998666, 
]

times.extend(times_67)

coverages_67 = [
    [2.08062229279719e-08, 0.31917306371283927],
]

coverages.extend(coverages_67)


# -------------------- flush 68 ---------------------
times_68 = [
    1.3799999999998644, 
]

times.extend(times_68)

coverages_68 = [
    [2.0806222867027765e-08, 0.3191730643493552],
]

coverages.extend(coverages_68)


# -------------------- flush 69 ---------------------
times_69 = [
    1.3999999999998622, 
]

times.extend(times_69)

coverages_69 = [
    [2.0806222969805472e-08, 0.3191730632759635],
]

coverages.extend(coverages_69)


# -------------------- flush 70 ---------------------
times_70 = [
]

times.extend(times_70)

coverages_70 = [
]

coverages.extend(coverages_70)

