# KMC processes.
processes = [
    # CO adsorbed on bridge site.
    {
        "reaction": "CO_g + *_b -> CO_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [1.0, 0.0, 0.0],
                               [0.5, -0.5, 0.0],
                               [0.5, 0.0, 0.0]]],
        "elements_before": ["V", "V", "V", "V", "V"],
        "elements_after": ["V", "V", "V", "V", "C"],
        "basis_sites": [0],
    },
    {
        "reaction": "CO_g + *_b -> CO_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [-0.5, 0.5, 0.0],
                               [0.0, 1.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [0.0, 0.5, 0.0]]],
        "elements_before": ["V", "V", "V", "V", "V"],
        "elements_after": ["V", "V", "V", "V", "C"],
        "basis_sites": [0],
    },

    # O2 dissociative adsorption.
    {
        "reaction": "O2_g + 2*_b -> 2O_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [-0.5, 0.5, 0.0],
                               [0.0, 1.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [0.0, 0.5, 0.0],
                               [1.0, 0.0, 0.0],
                               [1.0, 1.0, 0.0],
                               [1.5, 0.5, 0.0],
                               [1.0, 0.5, 0.0]]
                              ],
        "elements_before": ["V", "V", "V", "V", "V", "V", "V", "V", "V"],
        "elements_after": ['V', 'V', 'V', 'V', 'O_s', 'V', 'V', 'V', 'O_s'],
        "basis_sites": [0],
    },
    {
        "reaction": "O2_g + 2*_b -> 2O_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [1.0, 0.0, 0.0],
                               [0.5, -0.5, 0.0],
                               [0.5, 0.0, 0.0],
                               [0.0, 1.0, 0.0],
                               [0.5, 1.5, 0.0],
                               [1.0, 1.0, 0.0],
                               [0.5, 1.0, 0.0]]
                              ],
        "elements_before": ["V", "V", "V", "V", "V", "V", "V", "V", "V"],
        "elements_after": ['V', 'V', 'V', 'V', 'O_s', 'V', 'V', 'V', 'O_s'],
        "basis_sites": [0],
    },

    # CO2_g associative desorption.
    {
        "reaction": "CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [1.0, 0.0, 0.0],
                               [0.5, -0.5, 0.0],
                               [0.5, 0.0, 0.0],
                               [-0.5, 0.5, 0.0],
                               [0.0, 1.0, 0.0],
                               [0.0, 0.5, 0.0]]
                              ],
        "elements_before": ['V', 'V', 'V', 'V', 'C', 'V', 'V', 'O_s'],
        "elements_after": ["V", "V", "V", "V", "V", "V", "V", "V"],
        "basis_sites": [0],
    },
    {
        "reaction": "CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [1.0, 0.0, 0.0],
                               [0.5, -0.5, 0.0],
                               [0.5, 0.0, 0.0],
                               [-0.5, 0.5, 0.0],
                               [0.0, 1.0, 0.0],
                               [0.0, 0.5, 0.0]]
                              ],
        "elements_before": ['V', 'V', 'V', 'V', 'O_s', 'V', 'V', 'C'],
        "elements_after": ["V", "V", "V", "V", "V", "V", "V", "V"],
        "basis_sites": [0],
    },

    {
        "reaction": "CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [1.0, 0.0, 0.0],
                               [0.5, -0.5, 0.0],
                               [0.5, 0.0, 0.0],
                               [1.0, 1.0, 0.0],
                               [1.5, 0.5, 0.0],
                               [1.0, 0.5, 0.0]]
                              ],
        "elements_before": ['V', 'V', 'V', 'V', 'C', 'V', 'V', 'O_s'],
        "elements_after": ["V", "V", "V", "V", "V", "V", "V", "V"],
        "basis_sites": [0],
    },
    {
        "reaction": "CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [1.0, 0.0, 0.0],
                               [0.5, -0.5, 0.0],
                               [0.5, 0.0, 0.0],
                               [1.0, 1.0, 0.0],
                               [1.5, 0.5, 0.0],
                               [1.0, 0.5, 0.0]]
                              ],
        "elements_before": ['V', 'V', 'V', 'V', 'O_s', 'V', 'V', 'C'],
        "elements_after": ["V", "V", "V", "V", "V", "V", "V", "V"],
        "basis_sites": [0],
    },

    {
        "reaction": "CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [-0.5, 0.5, 0.0],
                               [0.0, 1.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [0.0, 0.5, 0.0],
                               [0.5, 1.5, 0.0],
                               [1.0, 1.0, 0.0],
                               [0.5, 1.0, 0.0]]
                              ],
        "elements_before": ['V', 'V', 'V', 'V', 'C', 'V', 'V', 'O_s'],
        "elements_after": ["V", "V", "V", "V", "V", "V", "V", "V"],
        "basis_sites": [0],
    },
    {
        "reaction": "CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [-0.5, 0.5, 0.0],
                               [0.0, 1.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [0.0, 0.5, 0.0],
                               [0.5, 1.5, 0.0],
                               [1.0, 1.0, 0.0],
                               [0.5, 1.0, 0.0]]
                              ],
        "elements_before": ['V', 'V', 'V', 'V', 'O_s', 'V', 'V', 'C'],
        "elements_after": ["V", "V", "V", "V", "V", "V", "V", "V"],
        "basis_sites": [0],
    },

    {
        "reaction": "CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [-0.5, 0.5, 0.0],
                               [0.0, 1.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [0.0, 0.5, 0.0],
                               [-1.0, 1.0, 0.0],
                               [-0.5, 1.5, 0.0],
                               [-0.5, 1.0, 0.0]]
                              ],
        "elements_before": ['V', 'V', 'V', 'V', 'C', 'V', 'V', 'O_s'],
        "elements_after": ["V", "V", "V", "V", "V", "V", "V", "V"],
        "basis_sites": [0],
    },
    {
        "reaction": "CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [-0.5, 0.5, 0.0],
                               [0.0, 1.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [0.0, 0.5, 0.0],
                               [-1.0, 1.0, 0.0],
                               [-0.5, 1.5, 0.0],
                               [-0.5, 1.0, 0.0]]
                              ],
        "elements_before": ['V', 'V', 'V', 'V', 'O_s', 'V', 'V', 'C'],
        "elements_after": ["V", "V", "V", "V", "V", "V", "V", "V"],
        "basis_sites": [0],
    },

    # CO diffusion at basis site 0.
    {
        "reaction": "CO_b + *_t <-> CO_t + *_b -> CO_b + *_t",
        "coordinates_group": [[[0.0, 0.0, 0.0], [0.5, 0.0, 0.0]],
                              [[0.0, 0.0, 0.0], [0.0, 0.5, 0.0]],
                              [[0.0, 0.0, 0.0], [-0.5, 0.0, 0.0]],
                              [[0.0, 0.0, 0.0], [0.0, -0.5, 0.0]],
                              ],
        "elements_before": ["C", "V"],
        "elements_after": ["V", "C"],
        "basis_sites": [0],
        "fast": True,
    },

    # O diffusion.
    {
        "reaction": "O_b + *_t <-> O_t + *_b -> O_b + *_t",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [1.0, 0.0, 0.0],
                               [0.5, -0.5, 0.0],
                               [0.5, 0.0, 0.0],
                               [1.5, 0.5, 0.0],
                               [2.0, 0.0, 0.0],
                               [1.5, -0.5, 0.0],
                               [1.5, 0.0, 0.0]]
                              ],
        "elements_before": ['V', 'V', 'V', 'V', 'O_s', 'V', 'V', 'V', 'V'],
        "elements_after": ['V', 'V', 'V', 'V', 'V', 'V', 'V', 'V', 'O_s'],
        "basis_sites": [0],
    },

    {
        "reaction": "O_b + *_t <-> O_t + *_b -> O_b + *_t",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [-0.5, 0.5, 0.0],
                               [0.0, 1.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [0.0, 0.5, 0.0],
                               [0.0, -1.0, 0.0],
                               [-0.5, -0.5, 0.0],
                               [0.5, -0.5, 0.0],
                               [0.0, -0.5, 0.0]]
                              ],
        "elements_before": ['V', 'V', 'V', 'V', 'O_s', 'V', 'V', 'V', 'V'],
        "elements_after": ['V', 'V', 'V', 'V', 'V', 'V', 'V', 'V', 'O_s'],
        "basis_sites": [0],
    },

    # CO adsorbed on bridge site.
    {
        "reaction": "CO_g + *_b -> CO_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [1.0, 0.0, 0.0],
                               [0.5, -0.5, 0.0],
                               [0.5, 0.0, 0.0]]],
        "elements_before": ["V", "V", "V", "V", "V"],
        "elements_after": ["V", "V", "V", "V", "C"],
        "basis_sites": [0],
        "fast": True,
        "redist": True,
        "redist_species": "C"
    },
    {
        "reaction": "CO_g + *_b -> CO_b",
        "coordinates_group": [[[0.0, 0.0, 0.0],
                               [-0.5, 0.5, 0.0],
                               [0.0, 1.0, 0.0],
                               [0.5, 0.5, 0.0],
                               [0.0, 0.5, 0.0]]],
        "elements_before": ["V", "V", "V", "V", "V"],
        "elements_after": ["V", "V", "V", "V", "C"],
        "basis_sites": [0],
        "fast": True,
        "redist": True,
        "redist_species": "C"
    },
]
