# This file was automatically generated by scaks (https://github.com/PytLab/scaks).
# Version 0.1.0
# Date: Wed Oct 23 19:31:23 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    138993, 138913, 79, 0, 196515, 
    196436, 79, 0, 79, 0, 
    162159, 162097, 62, 0, 62, 
    0, 2232, 2170, 62, 0, 
    62, 0, 
]

reaction_occurencies = {
    'CH3_c + *_b <-> CH3-_c + *_b -> CH3_b + *_c(->)': 79,
    'CH3_c + *_b <-> CH3-_c + *_b -> CH3_b + *_c(<-)': 0,
    'CH4_g + *_a + *_c <-> CH3-H_c + *_a -> CH3_c + H_a(->)': 138993,
    'CH4_g + *_a + *_c <-> CH3-H_c + *_a -> CH3_c + H_a(<-)': 138913,
    'CHO_c + *_b <-> CHO-_c + *_b -> CHO_b + *_c(->)': 62,
    'CHO_c + *_b <-> CHO-_c + *_b -> CHO_b + *_c(<-)': 0,
    'O2_c + CH3_b <-> OO-H_c + CH2_b -> OOH_c + CH2_b(->)': 79,
    'O2_c + CH3_b <-> OO-H_c + CH2_b -> OOH_c + CH2_b(<-)': 0,
    'O2_c + CHO_b + O_v <-> OO-H_c + CO_b + O_v -> OOH_c + CO2_g + *_b + *_v(->)': 62,
    'O2_c + CHO_b + O_v <-> OO-H_c + CO_b + O_v -> OOH_c + CO2_g + *_b + *_v(<-)': 0,
    'O2_g + *_c + CH3_b -> O2_c + CH3_b(->)': 196515,
    'O2_g + *_c + CH3_b -> O2_c + CH3_b(<-)': 196436,
    'O2_g + CHO_b + *_c -> O2_c + CHO_b(->)': 2232,
    'O2_g + CHO_b + *_c -> O2_c + CHO_b(<-)': 2170,
    'OCH2_b + *_c <-> OCH2-_b + *_c -> *_b + OCH2_c(->)': 162159,
    'OCH2_b + *_c <-> OCH2-_b + *_c -> *_b + OCH2_c(<-)': 162097,
    'OCH2_c + *_a <-> OCH-H_c + *_a -> CHO_c + H_a(->)': 62,
    'OCH2_c + *_a <-> OCH-H_c + *_a -> CHO_c + H_a(<-)': 0,
    'OOH_c + H_a + *_v -> H2O_g + *_c + *_a + O_v(->)': 62,
    'OOH_c + H_a + *_v -> H2O_g + *_c + *_a + O_v(<-)': 0,
    'OOH_c + H_a + CH2_b <-> OOH-H_c + *_a + CH2_b -> H2O_g + OCH2_b + *_a + *_c(->)': 79,
    'OOH_c + H_a + CH2_b <-> OOH-H_c + *_a + CH2_b -> H2O_g + OCH2_b + *_a + *_c(<-)': 0,
}

steady_reaction_occurencies = {
    'CH3_c + *_b <-> CH3-_c + *_b -> CH3_b + *_c(->)': 79,
    'CH3_c + *_b <-> CH3-_c + *_b -> CH3_b + *_c(<-)': 0,
    'CH4_g + *_a + *_c <-> CH3-H_c + *_a -> CH3_c + H_a(->)': 138993,
    'CH4_g + *_a + *_c <-> CH3-H_c + *_a -> CH3_c + H_a(<-)': 138913,
    'CHO_c + *_b <-> CHO-_c + *_b -> CHO_b + *_c(->)': 62,
    'CHO_c + *_b <-> CHO-_c + *_b -> CHO_b + *_c(<-)': 0,
    'O2_c + CH3_b <-> OO-H_c + CH2_b -> OOH_c + CH2_b(->)': 79,
    'O2_c + CH3_b <-> OO-H_c + CH2_b -> OOH_c + CH2_b(<-)': 0,
    'O2_c + CHO_b + O_v <-> OO-H_c + CO_b + O_v -> OOH_c + CO2_g + *_b + *_v(->)': 62,
    'O2_c + CHO_b + O_v <-> OO-H_c + CO_b + O_v -> OOH_c + CO2_g + *_b + *_v(<-)': 0,
    'O2_g + *_c + CH3_b -> O2_c + CH3_b(->)': 196515,
    'O2_g + *_c + CH3_b -> O2_c + CH3_b(<-)': 196436,
    'O2_g + CHO_b + *_c -> O2_c + CHO_b(->)': 2232,
    'O2_g + CHO_b + *_c -> O2_c + CHO_b(<-)': 2170,
    'OCH2_b + *_c <-> OCH2-_b + *_c -> *_b + OCH2_c(->)': 162159,
    'OCH2_b + *_c <-> OCH2-_b + *_c -> *_b + OCH2_c(<-)': 162097,
    'OCH2_c + *_a <-> OCH-H_c + *_a -> CHO_c + H_a(->)': 62,
    'OCH2_c + *_a <-> OCH-H_c + *_a -> CHO_c + H_a(<-)': 0,
    'OOH_c + H_a + *_v -> H2O_g + *_c + *_a + O_v(->)': 62,
    'OOH_c + H_a + *_v -> H2O_g + *_c + *_a + O_v(<-)': 0,
    'OOH_c + H_a + CH2_b <-> OOH-H_c + *_a + CH2_b -> H2O_g + OCH2_b + *_a + *_c(->)': 79,
    'OOH_c + H_a + CH2_b <-> OOH-H_c + *_a + CH2_b -> H2O_g + OCH2_b + *_a + *_c(<-)': 0,
}

reaction_rates = {
    'CH3_c + *_b <-> CH3-_c + *_b -> CH3_b + *_c(->)': 5.534504772638419e-06,
    'CH3_c + *_b <-> CH3-_c + *_b -> CH3_b + *_c(<-)': 0.0,
    'CH4_g + *_a + *_c <-> CH3-H_c + *_a -> CH3_c + H_a(->)': 0.00973743571978901,
    'CH4_g + *_a + *_c <-> CH3-H_c + *_a -> CH3_c + H_a(<-)': 0.009731831157993934,
    'CHO_c + *_b <-> CHO-_c + *_b -> CHO_b + *_c(->)': 4.343535391184582e-06,
    'CHO_c + *_b <-> CHO-_c + *_b -> CHO_b + *_c(<-)': 0.0,
    'O2_c + CH3_b <-> OO-H_c + CH2_b -> OOH_c + CH2_b(->)': 5.534504772638419e-06,
    'O2_c + CH3_b <-> OO-H_c + CH2_b -> OOH_c + CH2_b(<-)': 0.0,
    'O2_c + CHO_b + O_v <-> OO-H_c + CO_b + O_v -> OOH_c + CO2_g + *_b + *_v(->)': 4.343535391184582e-06,
    'O2_c + CHO_b + O_v <-> OO-H_c + CO_b + O_v -> OOH_c + CO2_g + *_b + *_v(<-)': 0.0,
    'O2_g + *_c + CH3_b -> O2_c + CH3_b(->)': 0.013767255764494163,
    'O2_g + *_c + CH3_b -> O2_c + CH3_b(<-)': 0.013761721259721525,
    'O2_g + CHO_b + *_c -> O2_c + CHO_b(->)': 0.00015636727408264496,
    'O2_g + CHO_b + *_c -> O2_c + CHO_b(<-)': 0.00015202373869146037,
    'OCH2_b + *_c <-> OCH2-_b + *_c -> *_b + OCH2_c(->)': 0.011360376701598398,
    'OCH2_b + *_c <-> OCH2-_b + *_c -> *_b + OCH2_c(<-)': 0.011356033166207213,
    'OCH2_c + *_a <-> OCH-H_c + *_a -> CHO_c + H_a(->)': 4.343535391184582e-06,
    'OCH2_c + *_a <-> OCH-H_c + *_a -> CHO_c + H_a(<-)': 0.0,
    'OOH_c + H_a + *_v -> H2O_g + *_c + *_a + O_v(->)': 4.343535391184582e-06,
    'OOH_c + H_a + *_v -> H2O_g + *_c + *_a + O_v(<-)': 0.0,
    'OOH_c + H_a + CH2_b <-> OOH-H_c + *_a + CH2_b -> H2O_g + OCH2_b + *_a + *_c(->)': 5.534504772638419e-06,
    'OOH_c + H_a + CH2_b <-> OOH-H_c + *_a + CH2_b -> H2O_g + OCH2_b + *_a + *_c(<-)': 0.0,
}

