# This file was automatically generated by scaks (https://github.com/PytLab/scaks).
# Version 0.1.0
# Date: Sat Jan 19 22:09:51 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []

coverages = []


# -------------------- flush 0 ---------------------
times_0 = [
]

times.extend(times_0)

coverages_0 = [
]

coverages.extend(coverages_0)

