# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 18:23:14 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14990600, 14969462, 3333, 0, 3431, 
    0, 3356, 0, 6816, 0, 
    6535, 0, 6889, 0, 1552, 
    1644, 1649, 1605, 1559, 1569, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4760,
    'CO_f + *_f -> CO_f + *_f(<-)': 4818,
    'CO_g + *_f -> CO_f(->)': 14990600,
    'CO_g + *_f -> CO_f(<-)': 14969462,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 10120,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 20240,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4760,
    'CO_f + *_f -> CO_f + *_f(<-)': 4818,
    'CO_g + *_f -> CO_f(->)': 14990600,
    'CO_g + *_f -> CO_f(<-)': 14969462,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 10120,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 20240,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.018106900181,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0183275304774,
    'CO_g + *_f -> CO_f(->)': 57.0238020702,
    'CO_g + *_f -> CO_f(<-)': 56.9433937391,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0384961827379,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0769923654757,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

