# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Fri Jan  4 14:34:40 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    6018, 6054, 44424, 43483, 3, 
    0, 2, 0, 1, 0, 
    1, 0, 2, 0, 0, 
    0, 1, 0, 1, 0, 
    4, 0, 1, 0, 2, 
    0, 3, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 
]

reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 44424,
    'CO_g + *_f -> CO_f(<-)': 43483,
    'CO_g + *_h -> CO_h(->)': 6018,
    'CO_g + *_h -> CO_h(<-)': 6054,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 6,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 3,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0,
    'O_f + *_h -> O_h + *_f(->)': 0,
    'O_f + *_h -> O_h + *_f(<-)': 0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 6,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 6,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 44424,
    'CO_g + *_f -> CO_f(<-)': 43483,
    'CO_g + *_h -> CO_h(->)': 6018,
    'CO_g + *_h -> CO_h(<-)': 6054,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 6,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 3,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0,
    'O_f + *_h -> O_h + *_f(->)': 0,
    'O_f + *_h -> O_h + *_f(<-)': 0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 6,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 6,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0,
}

reaction_rates = {
    'CO_g + *_f -> CO_f(->)': 53.4105099947,
    'CO_g + *_f -> CO_f(<-)': 52.2791555488,
    'CO_g + *_h -> CO_h(->)': 7.23537837989,
    'CO_g + *_h -> CO_h(<-)': 7.2786608029,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00721373716838,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 0.00360686858419,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0.0,
    'O_f + *_h -> O_h + *_f(->)': 0.0,
    'O_f + *_h -> O_h + *_f(<-)': 0.0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 0.00721373716838,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0.0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 0.00721373716838,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0.0,
}

