# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 19:48:50 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    5000180, 4999099, 32, 0, 24, 
    0, 35, 0, 65, 0, 
    71, 0, 46, 0, 66, 
    64, 67, 76, 82, 93, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 215,
    'CO_f + *_f -> CO_f + *_f(<-)': 233,
    'CO_g + *_f -> CO_f(->)': 5000180,
    'CO_g + *_f -> CO_f(<-)': 4999099,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 91,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 182,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 215,
    'CO_f + *_f -> CO_f + *_f(<-)': 233,
    'CO_g + *_f -> CO_f(->)': 5000180,
    'CO_g + *_f -> CO_f(<-)': 4999099,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 91,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 182,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00245630021968,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00266194395901,
    'CO_g + *_f -> CO_f(->)': 57.1253173603,
    'CO_g + *_f -> CO_f(<-)': 57.1129673113,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0010396433488,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00207928669759,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

