# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 21:47:49 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    4999661, 4997843, 145, 0, 150, 
    0, 166, 0, 319, 0, 
    313, 0, 290, 0, 182, 
    172, 203, 167, 178, 211, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 563,
    'CO_f + *_f -> CO_f + *_f(<-)': 550,
    'CO_g + *_f -> CO_f(->)': 4999661,
    'CO_g + *_f -> CO_f(<-)': 4997843,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 461,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 922,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 563,
    'CO_f + *_f -> CO_f + *_f(<-)': 550,
    'CO_g + *_f -> CO_f(->)': 4999661,
    'CO_g + *_f -> CO_f(<-)': 4997843,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 461,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 922,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00643015666044,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00628168057415,
    'CO_g + *_f -> CO_f(->)': 57.1023152382,
    'CO_g + *_f -> CO_f(<-)': 57.0815514286,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00526519044487,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0105303808897,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

