# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Wed Jan 23 20:09:14 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    200037, 0, 199727, 0, 100304, 
    0, 100172, 0, 50623, 0, 
    50549, 0, 49802, 0, 49652, 
    0, 49767, 0, 49913, 0, 
    49783, 0, 49669, 0, 1, 
    1, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 
]

reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 399758,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 399764,
    'CO_g + *_b -> CO_b(<-)': 0,
    'O2_g + 2*_b -> 2O_b(->)': 200476,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 1,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 1,
}

steady_reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 399758,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 399764,
    'CO_g + *_b -> CO_b(<-)': 0,
    'O2_g + 2*_b -> 2O_b(->)': 200476,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 1,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 1,
}

reaction_rates = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 992392.304431,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0.0,
    'CO_g + *_b -> CO_b(->)': 992407.199327,
    'CO_g + *_b -> CO_b(<-)': 0.0,
    'O2_g + 2*_b -> 2O_b(->)': 497678.194365,
    'O2_g + 2*_b -> 2O_b(<-)': 0.0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 2.48248266309,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 2.48248266309,
}

