# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 21:47:50 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    4999948, 4998519, 105, 0, 70, 
    0, 91, 0, 177, 0, 
    178, 0, 177, 0, 108, 
    122, 123, 103, 134, 145, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 365,
    'CO_f + *_f -> CO_f + *_f(<-)': 370,
    'CO_g + *_f -> CO_f(->)': 4999948,
    'CO_g + *_f -> CO_f(<-)': 4998519,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 266,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 532,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 365,
    'CO_f + *_f -> CO_f + *_f(<-)': 370,
    'CO_g + *_f -> CO_f(->)': 4999948,
    'CO_g + *_f -> CO_f(<-)': 4998519,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 266,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 532,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0041682510564,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00422535038594,
    'CO_g + *_f -> CO_f(->)': 57.0987357067,
    'CO_g + *_f -> CO_f(<-)': 57.0824167183,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00303768433151,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00607536866302,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

