# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 23:29:30 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14993261, 14982667, 1599, 0, 1628, 
    0, 1621, 0, 3278, 0, 
    3105, 0, 3313, 0, 1513, 
    1636, 1634, 1629, 1549, 1567, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4696,
    'CO_f + *_f -> CO_f + *_f(<-)': 4832,
    'CO_g + *_f -> CO_f(->)': 14993261,
    'CO_g + *_f -> CO_f(<-)': 14982667,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 4848,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 9696,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4696,
    'CO_f + *_f -> CO_f + *_f(<-)': 4832,
    'CO_g + *_f -> CO_f(->)': 14993261,
    'CO_g + *_f -> CO_f(<-)': 14982667,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 4848,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 9696,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0178496084959,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0183665477539,
    'CO_g + *_f -> CO_f(->)': 56.9897442348,
    'CO_g + *_f -> CO_f(<-)': 56.9494761871,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0184273641372,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0368547282743,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

