# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Mon May 22 14:40:03 2017 
#
# Do not make changes to this file unless you know what you are doing

times = []

coverages = []


# -------------------- flush 0 ---------------------
times_0 = [
    0.014844031527269194, 
]

times.extend(times_0)

coverages_0 = [
    [1.2838643856302346e-07, 0.07060929102367007],
]

coverages.extend(coverages_0)


# -------------------- flush 1 ---------------------
times_1 = [
    0.029844031527269207, 
]

times.extend(times_1)

coverages_1 = [
    [6.954897573502005e-08, 0.12299655271802672],
]

coverages.extend(coverages_1)


# -------------------- flush 2 ---------------------
times_2 = [
    0.04484403152726922, 
]

times.extend(times_2)

coverages_2 = [
    [5.027737524563695e-08, 0.16248118844633377],
]

coverages.extend(coverages_2)


# -------------------- flush 3 ---------------------
times_3 = [
    0.059844031527269234, 
]

times.extend(times_3)

coverages_3 = [
    [4.0817984968466294e-08, 0.1928742754378343],
]

coverages.extend(coverages_3)


# -------------------- flush 4 ---------------------
times_4 = [
    0.07484403152726925, 
]

times.extend(times_4)

coverages_4 = [
    [3.5267862178353425e-08, 0.21665028939597206],
]

coverages.extend(coverages_4)


# -------------------- flush 5 ---------------------
times_5 = [
    0.08984403152726926, 
]

times.extend(times_5)

coverages_5 = [
    [3.166655963757227e-08, 0.2354865128526576],
]

coverages.extend(coverages_5)


# -------------------- flush 6 ---------------------
times_6 = [
    0.10484403152726927, 
]

times.extend(times_6)

coverages_6 = [
    [2.9174997543400465e-08, 0.2505588712546883],
]

coverages.extend(coverages_6)


# -------------------- flush 7 ---------------------
times_7 = [
    0.11984403152726929, 
]

times.extend(times_7)

coverages_7 = [
    [2.7373275572227105e-08, 0.26271615917068164],
]

coverages.extend(coverages_7)


# -------------------- flush 8 ---------------------
times_8 = [
    0.1348440315272693, 
]

times.extend(times_8)

coverages_8 = [
    [2.6029236401507434e-08, 0.27258554665219814],
]

coverages.extend(coverages_8)


# -------------------- flush 9 ---------------------
times_9 = [
    0.1498440315272693, 
]

times.extend(times_9)

coverages_9 = [
    [2.5002352274010865e-08, 0.28063919345651317],
]

coverages.extend(coverages_9)


# -------------------- flush 10 ---------------------
times_10 = [
    0.1648440315272693, 
]

times.extend(times_10)

coverages_10 = [
    [2.4203661639325494e-08, 0.2872397811647641],
]

coverages.extend(coverages_10)


# -------------------- flush 11 ---------------------
times_11 = [
    0.17984403152726933, 
]

times.extend(times_11)

coverages_11 = [
    [2.357380775749579e-08, 0.29266819648706044],
]

coverages.extend(coverages_11)


# -------------------- flush 12 ---------------------
times_12 = [
    0.19484403152726934, 
]

times.extend(times_12)

coverages_12 = [
    [2.307168464493786e-08, 0.2971451579369736],
]

coverages.extend(coverages_12)


# -------------------- flush 13 ---------------------
times_13 = [
    0.20984403152726935, 
]

times.extend(times_13)

coverages_13 = [
    [2.2667838908050573e-08, 0.30084638754461607],
]

coverages.extend(coverages_13)


# -------------------- flush 14 ---------------------
times_14 = [
    0.22484403152726937, 
]

times.extend(times_14)

coverages_14 = [
    [2.2340758231357534e-08, 0.30391228894552663],
]

coverages.extend(coverages_14)


# -------------------- flush 15 ---------------------
times_15 = [
    0.23984403152726938, 
]

times.extend(times_15)

coverages_15 = [
    [2.2074365837964024e-08, 0.30645593125143605],
]

coverages.extend(coverages_15)


# -------------------- flush 16 ---------------------
times_16 = [
    0.25484403152726937, 
]

times.extend(times_16)

coverages_16 = [
    [2.1856386667653992e-08, 0.3085691134492796],
]

coverages.extend(coverages_16)


# -------------------- flush 17 ---------------------
times_17 = [
    0.2698440315272694, 
]

times.extend(times_17)

coverages_17 = [
    [2.167740202160312e-08, 0.31032655302152445],
]

coverages.extend(coverages_17)


# -------------------- flush 18 ---------------------
times_18 = [
    0.2848440315272694, 
]

times.extend(times_18)

coverages_18 = [
    [2.1529979170608832e-08, 0.31178960219106566],
]

coverages.extend(coverages_18)


# -------------------- flush 19 ---------------------
times_19 = [
    0.2998440315272694, 
]

times.extend(times_19)

coverages_19 = [
    [2.1407766024935744e-08, 0.313008584476899],
]

coverages.extend(coverages_19)


# -------------------- flush 20 ---------------------
times_20 = [
    0.3148440315272694, 
]

times.extend(times_20)

coverages_20 = [
    [2.130730449376851e-08, 0.3140248114997735],
]

coverages.extend(coverages_20)


# -------------------- flush 21 ---------------------
times_21 = [
    0.32984403152726943, 
]

times.extend(times_21)

coverages_21 = [
    [2.1223454000232762e-08, 0.314872445061403],
]

coverages.extend(coverages_21)


# -------------------- flush 22 ---------------------
times_22 = [
    0.34484403152726945, 
]

times.extend(times_22)

coverages_22 = [
    [2.115416303779053e-08, 0.3155797945520769],
]

coverages.extend(coverages_22)


# -------------------- flush 23 ---------------------
times_23 = [
    0.35984403152726946, 
]

times.extend(times_23)

coverages_23 = [
    [2.1096466139221146e-08, 0.316170292109252],
]

coverages.extend(coverages_23)


# -------------------- flush 24 ---------------------
times_24 = [
    0.3748440315272695, 
]

times.extend(times_24)

coverages_24 = [
    [2.1048402208267995e-08, 0.316663388582117],
]

coverages.extend(coverages_24)


# -------------------- flush 25 ---------------------
times_25 = [
    0.3898440315272695, 
]

times.extend(times_25)

coverages_25 = [
    [2.1008387058104332e-08, 0.317075258718778],
]

coverages.extend(coverages_25)


# -------------------- flush 26 ---------------------
times_26 = [
    0.4048440315272695, 
]

times.extend(times_26)

coverages_26 = [
    [2.097504686251777e-08, 0.3174193639399784],
]

coverages.extend(coverages_26)


# -------------------- flush 27 ---------------------
times_27 = [
    0.4198440315272695, 
]

times.extend(times_27)

coverages_27 = [
    [2.0947235066715032e-08, 0.3177069009162674],
]

coverages.extend(coverages_27)


# -------------------- flush 28 ---------------------
times_28 = [
    0.4348440315272695, 
]

times.extend(times_28)

coverages_28 = [
    [2.0924029712361702e-08, 0.31794719480275296],
]

coverages.extend(coverages_28)


# -------------------- flush 29 ---------------------
times_29 = [
    0.44984403152726954, 
]

times.extend(times_29)

coverages_29 = [
    [2.0904663227286147e-08, 0.31814801473658166],
]

coverages.extend(coverages_29)


# -------------------- flush 30 ---------------------
times_30 = [
    0.46484403152726955, 
]

times.extend(times_30)

coverages_30 = [
    [2.0888495634679902e-08, 0.31831588951254736],
]

coverages.extend(coverages_30)


# -------------------- flush 31 ---------------------
times_31 = [
    0.47984403152726957, 
]

times.extend(times_31)

coverages_31 = [
    [2.0874990531646384e-08, 0.31845624172412385],
]

coverages.extend(coverages_31)


# -------------------- flush 32 ---------------------
times_32 = [
    0.4948440315272696, 
]

times.extend(times_32)

coverages_32 = [
    [2.0863708102230256e-08, 0.31857359194124885],
]

coverages.extend(coverages_32)


# -------------------- flush 33 ---------------------
times_33 = [
    0.5098440315272695, 
]

times.extend(times_33)

coverages_33 = [
    [2.0854279665348452e-08, 0.31867172329204757],
]

coverages.extend(coverages_33)


# -------------------- flush 34 ---------------------
times_34 = [
    0.5248440315272695, 
]

times.extend(times_34)

coverages_34 = [
    [2.0846399664298905e-08, 0.31875378440904556],
]

coverages.extend(coverages_34)


# -------------------- flush 35 ---------------------
times_35 = [
    0.5398440315272696, 
]

times.extend(times_35)

coverages_35 = [
    [2.0839813656437448e-08, 0.31882240336067386],
]

coverages.extend(coverages_35)


# -------------------- flush 36 ---------------------
times_36 = [
    0.5548440315272696, 
]

times.extend(times_36)

coverages_36 = [
    [2.083431148822642e-08, 0.31887975591589274],
]

coverages.extend(coverages_36)


# -------------------- flush 37 ---------------------
times_37 = [
    0.5698440315272696, 
]

times.extend(times_37)

coverages_37 = [
    [2.0829712084431072e-08, 0.3189277154895743],
]

coverages.extend(coverages_37)


# -------------------- flush 38 ---------------------
times_38 = [
    0.5848440315272696, 
]

times.extend(times_38)

coverages_38 = [
    [2.0825869199911272e-08, 0.31896779751814497],
]

coverages.extend(coverages_38)


# -------------------- flush 39 ---------------------
times_39 = [
    0.5998440315272696, 
]

times.extend(times_39)

coverages_39 = [
    [2.0822654760415288e-08, 0.3190013294684033],
]

coverages.extend(coverages_39)


# -------------------- flush 40 ---------------------
times_40 = [
    0.6148440315272696, 
]

times.extend(times_40)

coverages_40 = [
    [2.0819967809374256e-08, 0.31902937286913585],
]

coverages.extend(coverages_40)


# -------------------- flush 41 ---------------------
times_41 = [
    0.6298440315272696, 
]

times.extend(times_41)

coverages_41 = [
    [2.0817718822109464e-08, 0.31905284124968203],
]

coverages.extend(coverages_41)


# -------------------- flush 42 ---------------------
times_42 = [
    0.6448440315272697, 
]

times.extend(times_42)

coverages_42 = [
    [2.081583222613384e-08, 0.319072483271482],
]

coverages.extend(coverages_42)


# -------------------- flush 43 ---------------------
times_43 = [
    0.6598440315272697, 
]

times.extend(times_43)

coverages_43 = [
    [2.081425971051932e-08, 0.31908891651274657],
]

coverages.extend(coverages_43)


# -------------------- flush 44 ---------------------
times_44 = [
    0.6748440315272697, 
]

times.extend(times_44)

coverages_44 = [
    [2.0812956811359667e-08, 0.3191026699789199],
]

coverages.extend(coverages_44)


# -------------------- flush 45 ---------------------
times_45 = [
    0.6898440315272697, 
]

times.extend(times_45)

coverages_45 = [
    [2.0811836989886432e-08, 0.319114171376511],
]

coverages.extend(coverages_45)


# -------------------- flush 46 ---------------------
times_46 = [
    0.7048440315272697, 
]

times.extend(times_46)

coverages_46 = [
    [2.0810864814950112e-08, 0.319123787700185],
]

coverages.extend(coverages_46)


# -------------------- flush 47 ---------------------
times_47 = [
    0.7198440315272697, 
]

times.extend(times_47)

coverages_47 = [
    [2.0810094691286156e-08, 0.3191318129108983],
]

coverages.extend(coverages_47)


# -------------------- flush 48 ---------------------
times_48 = [
    0.7348440315272697, 
]

times.extend(times_48)

coverages_48 = [
    [2.0809508369928962e-08, 0.3191385378659084],
]

coverages.extend(coverages_48)


# -------------------- flush 49 ---------------------
times_49 = [
    0.7498440315272697, 
]

times.extend(times_49)

coverages_49 = [
    [2.0809008310647994e-08, 0.31914413648956036],
]

coverages.extend(coverages_49)


# -------------------- flush 50 ---------------------
times_50 = [
    0.7648440315272698, 
]

times.extend(times_50)

coverages_50 = [
    [2.08085532306718e-08, 0.31914882652328025],
]

coverages.extend(coverages_50)


# -------------------- flush 51 ---------------------
times_51 = [
    0.7798440315272698, 
]

times.extend(times_51)

coverages_51 = [
    [2.080813312152059e-08, 0.31915276089499817],
]

coverages.extend(coverages_51)


# -------------------- flush 52 ---------------------
times_52 = [
    0.7948440315272698, 
]

times.extend(times_52)

coverages_52 = [
    [2.0807805366513582e-08, 0.3191560476635609],
]

coverages.extend(coverages_52)


# -------------------- flush 53 ---------------------
times_53 = [
    0.8098440315272698, 
]

times.extend(times_53)

coverages_53 = [
    [2.080756708774475e-08, 0.31915881485456427],
]

coverages.extend(coverages_53)


# -------------------- flush 54 ---------------------
times_54 = [
    0.8248440315272698, 
]

times.extend(times_54)

coverages_54 = [
    [2.0807352354205788e-08, 0.31916112984370326],
]

coverages.extend(coverages_54)


# -------------------- flush 55 ---------------------
times_55 = [
    0.8398440315272698, 
]

times.extend(times_55)

coverages_55 = [
    [2.080716336369666e-08, 0.3191630734074633],
]

coverages.extend(coverages_55)


# -------------------- flush 56 ---------------------
times_56 = [
    0.8548440315272698, 
]

times.extend(times_56)

coverages_56 = [
    [2.0807001286245387e-08, 0.3191647024462093],
]

coverages.extend(coverages_56)


# -------------------- flush 57 ---------------------
times_57 = [
    0.8698440315272699, 
]

times.extend(times_57)

coverages_57 = [
    [2.080687024742675e-08, 0.31916606512393814],
]

coverages.extend(coverages_57)


# -------------------- flush 58 ---------------------
times_58 = [
    0.8848440315272699, 
]

times.extend(times_58)

coverages_58 = [
    [2.080676257021626e-08, 0.31916720549345023],
]

coverages.extend(coverages_58)


# -------------------- flush 59 ---------------------
times_59 = [
    0.8998440315272699, 
]

times.extend(times_59)

coverages_59 = [
    [2.080667167853386e-08, 0.31916815540915433],
]

coverages.extend(coverages_59)


# -------------------- flush 60 ---------------------
times_60 = [
    0.9148440315272699, 
]

times.extend(times_60)

coverages_60 = [
    [2.0806595368975657e-08, 0.31916895145946417],
]

coverages.extend(coverages_60)


# -------------------- flush 61 ---------------------
times_61 = [
    0.9298440315272699, 
]

times.extend(times_61)

coverages_61 = [
    [2.0806532984556395e-08, 0.3191696034940596],
]

coverages.extend(coverages_61)


# -------------------- flush 62 ---------------------
times_62 = [
    0.9448440315272699, 
]

times.extend(times_62)

coverages_62 = [
    [2.0806481680376167e-08, 0.31917014009676],
]

coverages.extend(coverages_62)


# -------------------- flush 63 ---------------------
times_63 = [
    0.9598440315272699, 
]

times.extend(times_63)

coverages_63 = [
    [2.080643847978172e-08, 0.3191705910706708],
]

coverages.extend(coverages_63)


# -------------------- flush 64 ---------------------
times_64 = [
    0.97484403152727, 
]

times.extend(times_64)

coverages_64 = [
    [2.0806401497132497e-08, 0.31917097586136456],
]

coverages.extend(coverages_64)


# -------------------- flush 65 ---------------------
times_65 = [
    0.98984403152727, 
]

times.extend(times_65)

coverages_65 = [
    [2.0806372319743047e-08, 0.3191712803599371],
]

coverages.extend(coverages_65)


# -------------------- flush 66 ---------------------
times_66 = [
]

times.extend(times_66)

coverages_66 = [
]

coverages.extend(coverages_66)

