# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Fri Jan  4 16:07:52 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    3084665, 3083672, 19, 0, 13, 
    0, 15, 0, 31, 0, 
    30, 0, 33, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 
]

reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 3084665,
    'CO_g + *_f -> CO_f(<-)': 3083672,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 47,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 94,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 3084665,
    'CO_g + *_f -> CO_f(<-)': 3083672,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 47,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 94,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_g + *_f -> CO_f(->)': 57.1234098547,
    'CO_g + *_f -> CO_f(<-)': 57.1050209709,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.000870370125498,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.001740740251,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

