# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 22:22:17 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    5000025, 4998800, 56, 0, 53, 
    0, 55, 0, 93, 0, 
    116, 0, 119, 0, 126, 
    107, 91, 113, 122, 124, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 339,
    'CO_f + *_f -> CO_f + *_f(<-)': 344,
    'CO_g + *_f -> CO_f(->)': 5000025,
    'CO_g + *_f -> CO_f(<-)': 4998800,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 164,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 328,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 339,
    'CO_f + *_f -> CO_f + *_f(<-)': 344,
    'CO_g + *_f -> CO_f(->)': 5000025,
    'CO_g + *_f -> CO_f(<-)': 4998800,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 164,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 328,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00387199244716,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0039291014803,
    'CO_g + *_f -> CO_f(->)': 57.1093186891,
    'CO_g + *_f -> CO_f(<-)': 57.0953269759,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00187317628712,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00374635257424,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

