# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 21:47:49 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    5000132, 4999047, 32, 0, 27, 
    0, 34, 0, 52, 0, 
    73, 0, 61, 0, 91, 
    90, 68, 88, 98, 107, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 257,
    'CO_f + *_f -> CO_f + *_f(<-)': 285,
    'CO_g + *_f -> CO_f(->)': 5000132,
    'CO_g + *_f -> CO_f(<-)': 4999047,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 93,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 186,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 257,
    'CO_f + *_f -> CO_f + *_f(<-)': 285,
    'CO_g + *_f -> CO_f(->)': 5000132,
    'CO_g + *_f -> CO_f(<-)': 4999047,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 93,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 186,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00293496261053,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00325472507394,
    'CO_g + *_f -> CO_f(->)': 57.1019473452,
    'CO_g + *_f -> CO_f(<-)': 57.0895565498,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00106206818202,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00212413636404,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

