# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 23:29:30 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14995648, 14994750, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1582, 
    1630, 1640, 1607, 1571, 1572, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4793,
    'CO_f + *_f -> CO_f + *_f(<-)': 4809,
    'CO_g + *_f -> CO_f(->)': 14995648,
    'CO_g + *_f -> CO_f(<-)': 14994750,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4793,
    'CO_f + *_f -> CO_f + *_f(<-)': 4809,
    'CO_g + *_f -> CO_f(->)': 14995648,
    'CO_g + *_f -> CO_f(<-)': 14994750,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0182014585186,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0182622186555,
    'CO_g + *_f -> CO_f(->)': 56.9461016131,
    'CO_g + *_f -> CO_f(<-)': 56.9426914504,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

