# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Wed Jan 23 15:11:21 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
steps = []
coverages = [[], [], [], [], [], [], []]

possible_types = [
    'O_u', 'O_d', 'O_l', 'O_r', 'V', 
    'O_s', 'C', 
]


# -------------------- flush 0 ---------------------
times_0 = [
    0.0, 2.13699021645e-07, 4.22348315601e-07, 6.68922738096e-07, 77170.5825919, 
    217561.460391, 355840.953137, 494633.329339, 
]

times.extend(times_0)

steps_0 = [
    0, 6666, 13332, 19998, 26664, 33330, 39996, 46662, 
]

steps.extend(steps_0)

coverages_0 = [
    (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (1.0, 0.8216666666666667, 0.8061111111111111, 0.5933333333333333, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.06388888888888888, 0.057777777777777775, 0.012777777777777779, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.11444444444444445, 0.1361111111111111, 0.3938888888888889, 1.0, 1.0, 1.0, 1.0),
]

coverages[0].extend(coverages_0[0])
coverages[1].extend(coverages_0[1])
coverages[2].extend(coverages_0[2])
coverages[3].extend(coverages_0[3])
coverages[4].extend(coverages_0[4])
coverages[5].extend(coverages_0[5])
coverages[6].extend(coverages_0[6])
