# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 22:22:17 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    4999789, 4998206, 108, 0, 100, 
    0, 135, 0, 228, 0, 
    229, 0, 229, 0, 159, 
    153, 170, 132, 175, 187, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 504,
    'CO_f + *_f -> CO_f + *_f(<-)': 472,
    'CO_g + *_f -> CO_f(->)': 4999789,
    'CO_g + *_f -> CO_f(<-)': 4998206,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 343,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 686,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 504,
    'CO_f + *_f -> CO_f + *_f(<-)': 472,
    'CO_g + *_f -> CO_f(->)': 4999789,
    'CO_g + *_f -> CO_f(<-)': 4998206,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 343,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 686,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00575524770975,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00538983515675,
    'CO_g + *_f -> CO_f(->)': 57.0933019672,
    'CO_g + *_f -> CO_f(<-)': 57.075225465,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00391676580247,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00783353160494,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

