# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Fri Jan  4 14:39:33 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    3136, 3133, 47304, 46406, 3, 
    0, 0, 0, 4, 0, 
    3, 0, 0, 0, 0, 
    0, 1, 0, 4, 0, 
    1, 0, 1, 0, 3, 
    0, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 
]

reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 47304,
    'CO_g + *_f -> CO_f(<-)': 46406,
    'CO_g + *_h -> CO_h(->)': 3136,
    'CO_g + *_h -> CO_h(<-)': 3133,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 7,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 3,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0,
    'O_f + *_h -> O_h + *_f(->)': 0,
    'O_f + *_h -> O_h + *_f(<-)': 0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 5,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 6,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 47304,
    'CO_g + *_f -> CO_f(<-)': 46406,
    'CO_g + *_h -> CO_h(->)': 3136,
    'CO_g + *_h -> CO_h(<-)': 3133,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 7,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 3,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0,
    'O_f + *_h -> O_h + *_f(->)': 0,
    'O_f + *_h -> O_h + *_f(<-)': 0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 5,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 6,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0,
}

reaction_rates = {
    'CO_g + *_f -> CO_f(->)': 55.2843435964,
    'CO_g + *_f -> CO_f(<-)': 54.2348479819,
    'CO_g + *_h -> CO_h(->)': 3.66505372734,
    'CO_g + *_h -> CO_h(<-)': 3.66154761727,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00818092349854,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 0.0035061100708,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0.0,
    'O_f + *_h -> O_h + *_f(->)': 0.0,
    'O_f + *_h -> O_h + *_f(<-)': 0.0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 0.00584351678467,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0.0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 0.0070122201416,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0.0,
}

