# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Wed Jan 23 15:11:23 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    200195, 0, 199634, 0, 100337, 
    0, 100015, 0, 52694, 0, 
    52071, 0, 49417, 0, 49102, 
    0, 49224, 0, 49313, 0, 
    49196, 0, 48801, 0, 1, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 
]

reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 399818,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 399829,
    'CO_g + *_b -> CO_b(<-)': 0,
    'O2_g + 2*_b -> 2O_b(->)': 200352,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 1,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 399818,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 399829,
    'CO_g + *_b -> CO_b(<-)': 0,
    'O2_g + 2*_b -> 2O_b(->)': 200352,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 1,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0,
}

reaction_rates = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 2329412.62399,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0.0,
    'CO_g + *_b -> CO_b(->)': 2329476.712,
    'CO_g + *_b -> CO_b(<-)': 0.0,
    'O2_g + 2*_b -> 2O_b(->)': 1167287.31083,
    'O2_g + 2*_b -> 2O_b(<-)': 0.0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 5.826182473,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0.0,
}

