# This file was automatically generated by scaks (https://github.com/PytLab/scaks) powered by KMCLibX.
# Version 0.1.0
# Date: Sun Sep 29 16:13:01 2019 
#
# Do not make changes to this file unless you know what you are doing

from KMCLib import *


# -----------------------------------------------------------------------------
# Unit cell

cell_vectors = [[   1.000000e+00,   0.000000e+00,   0.000000e+00],
                [   0.000000e+00,   1.000000e+00,   0.000000e+00],
                [   0.000000e+00,   0.000000e+00,   1.000000e+00]]

basis_points = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
                [   4.000000e-01,   0.000000e+00,   0.000000e+00],
                [   8.000000e-01,   0.000000e+00,   0.000000e+00],
                [   0.000000e+00,   5.000000e-01,   0.000000e+00],
                [   4.000000e-01,   5.000000e-01,   0.000000e+00],
                [   8.000000e-01,   5.000000e-01,   0.000000e+00]]

unit_cell = KMCUnitCell(
    cell_vectors=cell_vectors,
    basis_points=basis_points)

# -----------------------------------------------------------------------------
# Lattice

lattice = KMCLattice(
    unit_cell=unit_cell,
    repetitions=(10,10,1),
    periodic=(True, True, False))

# -----------------------------------------------------------------------------
# Configuration

types = ['*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o','*_o','*_c','*_o',
         '*_o','*_c','*_o','*_o','*_c','*_o']

possible_types = ['*_c','*_o','*_v','-CH2_o','CH3_c','CH3_o','CHO_o',
                  'H_o','O2_c','OH_c','OOH_c','O_c']

configuration = KMCConfiguration(
    lattice=lattice,
    types=types,
    possible_types=possible_types)

# -----------------------------------------------------------------------------
# Unit cell

cell_vectors = [[   1.000000e+00,   0.000000e+00,   0.000000e+00],
                [   0.000000e+00,   1.000000e+00,   0.000000e+00],
                [   0.000000e+00,   0.000000e+00,   1.000000e+00]]

basis_points = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
                [   4.000000e-01,   0.000000e+00,   0.000000e+00],
                [   8.000000e-01,   0.000000e+00,   0.000000e+00],
                [   0.000000e+00,   5.000000e-01,   0.000000e+00],
                [   4.000000e-01,   5.000000e-01,   0.000000e+00],
                [   8.000000e-01,   5.000000e-01,   0.000000e+00]]

unit_cell = KMCUnitCell(
    cell_vectors=cell_vectors,
    basis_points=basis_points)

# -----------------------------------------------------------------------------
# Lattice

lattice = KMCLattice(
    unit_cell=unit_cell,
    repetitions=(10,10,1),
    periodic=(True, True, False))

# -----------------------------------------------------------------------------
# SitesMap

types = ['P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P','P','P','P','P','P','P','P','P','P','P','P',
         'P','P']

possible_types = ['P']

sitesmap = KMCSitesMap(
    lattice=lattice,
    types=types,
    possible_types=possible_types)

# -----------------------------------------------------------------------------
# Interactions

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['*_o','*_c']
elements_after  = ['H_o','CH3_c']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    1.259699e-03

process_0 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['H_o','CH3_c']
elements_after  = ['*_o','*_c']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    1.057034e+05

process_1 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['*','CH3_c','*_o']
elements_after  = ['*','*_c','CH3_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    8.049585e+06

process_2 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['*','*_c','CH3_o']
elements_after  = ['*','CH3_c','*_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    8.641141e-01

process_3 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00]]

elements_before = ['*_o','CH3_o','*_o']
elements_after  = ['H_o','-CH2_o','-CH2_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    1.049170e+08

process_4 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00]]

elements_before = ['H_o','-CH2_o','-CH2_o']
elements_after  = ['*_o','CH3_o','*_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    6.629774e-02

process_5 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','*_c','-CH2_o','-CH2_o']
elements_after  = ['*','O2_c','-CH2_o','-CH2_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    3.013600e+12

process_6 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','O2_c','-CH2_o','-CH2_o']
elements_after  = ['*','*_c','-CH2_o','-CH2_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    8.449717e+08

process_7 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','O2_c','-CH2_o','-CH2_o']
elements_after  = ['*','OH_c','*_o','CHO_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    1.049170e+08

process_8 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','OH_c','*_o','CHO_o']
elements_after  = ['*','O2_c','-CH2_o','-CH2_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    5.796241e+09

process_9 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00],
               [   4.000000e-01,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','CHO_o','*_c']
elements_after  = ['*','CHO_o','O2_c']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    3.013600e+12

process_10 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00],
               [   4.000000e-01,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','CHO_o','O2_c']
elements_after  = ['*','CHO_o','*_c']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    8.449717e+08

process_11 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00],
               [   4.000000e-01,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','CHO_o','O2_c']
elements_after  = ['*','*_v','OOH_c']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    1.710665e+05

process_12 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00],
               [   4.000000e-01,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','*_v','OOH_c']
elements_after  = ['*','CHO_o','O2_c']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    6.907556e+01

process_13 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','OH_c','CHO_o']
elements_after  = ['*','*_c','*_v']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    4.236482e+06

process_14 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','*_c','*_v']
elements_after  = ['*','OH_c','CHO_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    2.303575e-12

process_15 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','*_o','CHO_o']
elements_after  = ['*','H_o','*_v']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    3.250372e+05

process_16 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','H_o','*_v']
elements_after  = ['*','*_o','CHO_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    7.415186e-06

process_17 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','*_c','*_v']
elements_after  = ['*','O_c','*_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    3.013600e+12

process_18 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.000000e+00,   0.000000e+00]]

elements_before = ['*','O_c','*_o']
elements_after  = ['*','*_c','*_v']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    4.480403e+05

process_19 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['H_o','*_o']
elements_after  = ['*_o','H_o']
site_types = None
move_vectors    = [(  0,[   8.000000e-01,   5.000000e-01,   0.000000e+00]),
                   (  1,[  -8.000000e-01,  -5.000000e-01,   0.000000e+00])]
basis_sites     = [0]
rate_constant   =    4.936901e+09

process_20 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['*_o','H_o']
elements_after  = ['H_o','*_o']
site_types = None
move_vectors    = [(  0,[   8.000000e-01,   5.000000e-01,   0.000000e+00]),
                   (  1,[  -8.000000e-01,  -5.000000e-01,   0.000000e+00])]
basis_sites     = [0]
rate_constant   =    4.936901e+09

process_21 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   8.000000e-01,  -5.000000e-01,   0.000000e+00]]

elements_before = ['H_o','*_o']
elements_after  = ['*_o','H_o']
site_types = None
move_vectors    = [(  0,[   8.000000e-01,  -5.000000e-01,   0.000000e+00]),
                   (  1,[  -8.000000e-01,   5.000000e-01,   0.000000e+00])]
basis_sites     = [0]
rate_constant   =    4.936901e+09

process_22 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   8.000000e-01,  -5.000000e-01,   0.000000e+00]]

elements_before = ['*_o','H_o']
elements_after  = ['H_o','*_o']
site_types = None
move_vectors    = [(  0,[   8.000000e-01,  -5.000000e-01,   0.000000e+00]),
                   (  1,[  -8.000000e-01,   5.000000e-01,   0.000000e+00])]
basis_sites     = [0]
rate_constant   =    4.936901e+09

process_23 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   0.000000e+00,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.500000e+00,   0.000000e+00]]

elements_before = ['*','H_o','*_o']
elements_after  = ['*','*_o','H_o']
site_types = None
move_vectors    = [(  1,[   0.000000e+00,   1.000000e+00,   0.000000e+00]),
                   (  2,[   0.000000e+00,  -1.000000e+00,   0.000000e+00])]
basis_sites     = [0]
rate_constant   =    5.839685e+06

process_24 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   0.000000e+00,   5.000000e-01,   0.000000e+00],
               [   0.000000e+00,   1.500000e+00,   0.000000e+00]]

elements_before = ['*','*_o','H_o']
elements_after  = ['*','H_o','*_o']
site_types = None
move_vectors    = [(  1,[   0.000000e+00,   1.000000e+00,   0.000000e+00]),
                   (  2,[   0.000000e+00,  -1.000000e+00,   0.000000e+00])]
basis_sites     = [0]
rate_constant   =    5.839685e+06

process_25 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['*','O_c','H_o']
elements_after  = ['*','OH_c','*_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    4.936901e+09

process_26 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['*','OH_c','*_o']
elements_after  = ['*','O_c','H_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    9.450733e+06

process_27 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   0.000000e+00,   5.000000e-01,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['*','H_o','O_c']
elements_after  = ['*','*_o','OH_c']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    4.936901e+09

process_28 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   0.000000e+00,   5.000000e-01,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['*','*_o','OH_c']
elements_after  = ['*','H_o','O_c']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    1.302715e+07

process_29 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['*','OH_c','H_o']
elements_after  = ['*','*_c','*_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    4.936901e+09

process_30 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00],
               [   8.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['*','*_c','*_o']
elements_after  = ['*','OH_c','H_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    2.796902e-02

process_31 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   0.000000e+00,   5.000000e-01,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['*','H_o','OH_c']
elements_after  = ['*','*_o','*_c']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    4.936901e+09

process_32 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00],
               [   0.000000e+00,   5.000000e-01,   0.000000e+00],
               [   4.000000e-01,   5.000000e-01,   0.000000e+00]]

elements_before = ['*','*_o','*_c']
elements_after  = ['*','H_o','OH_c']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    1.391866e-01

process_33 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00]]

elements_before = ['*_o']
elements_after  = ['H_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    1.259699e-03

process_34 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

coordinates = [[   0.000000e+00,   0.000000e+00,   0.000000e+00]]

elements_before = ['*_o']
elements_after  = ['H_o']
site_types = None
move_vectors    = None
basis_sites     = [0]
rate_constant   =    1.259699e-03

process_35 = KMCProcess(
    coordinates=coordinates,
    elements_before=elements_before,
    elements_after=elements_after,
    move_vectors=move_vectors,
    basis_sites=basis_sites,
    rate_constant=rate_constant,
    site_types=site_types)

processes = [process_0,
             process_1,
             process_2,
             process_3,
             process_4,
             process_5,
             process_6,
             process_7,
             process_8,
             process_9,
             process_10,
             process_11,
             process_12,
             process_13,
             process_14,
             process_15,
             process_16,
             process_17,
             process_18,
             process_19,
             process_20,
             process_21,
             process_22,
             process_23,
             process_24,
             process_25,
             process_26,
             process_27,
             process_28,
             process_29,
             process_30,
             process_31,
             process_32,
             process_33,
             process_34,
             process_35]

interactions = KMCInteractions(
    processes=processes,
    sitesmap=None,
    implicit_wildcards=True)

# -----------------------------------------------------------------------------
# Lattice model

model = KMCLatticeModel(
    configuration=configuration,
    sitesmap=sitesmap,
    interactions=interactions)
