# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 21:47:49 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    5000052, 4998829, 50, 0, 61, 
    0, 51, 0, 90, 0, 
    115, 0, 119, 0, 98, 
    112, 84, 98, 116, 125, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 298,
    'CO_f + *_f -> CO_f + *_f(<-)': 335,
    'CO_g + *_f -> CO_f(->)': 5000052,
    'CO_g + *_f -> CO_f(<-)': 4998829,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 162,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 324,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 298,
    'CO_f + *_f -> CO_f + *_f(<-)': 335,
    'CO_g + *_f -> CO_f(->)': 5000052,
    'CO_g + *_f -> CO_f(<-)': 4998829,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 162,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 324,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00340388159761,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00382651119195,
    'CO_g + *_f -> CO_f(->)': 57.1127013084,
    'CO_g + *_f -> CO_f(<-)': 57.098731687,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0018504322779,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.00370086455579,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

