# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 20:30:35 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    1407, 338, 26, 0, 34, 
    0, 25, 0, 55, 0, 
    47, 0, 68, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 0,
    'CO_f + *_f -> CO_f + *_f(<-)': 0,
    'CO_g + *_f -> CO_f(->)': 1407,
    'CO_g + *_f -> CO_f(<-)': 338,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 85,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 170,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 0,
    'CO_f + *_f -> CO_f + *_f(<-)': 0,
    'CO_g + *_f -> CO_f(->)': 1407,
    'CO_g + *_f -> CO_f(<-)': 338,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 85,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 170,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0,
    'CO_g + *_f -> CO_f(->)': 230.740071691,
    'CO_g + *_f -> CO_f(<-)': 55.4300954027,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 13.9395210332,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 27.8790420665,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

