# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 01:25:25 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    5000090, 4998905, 42, 0, 50, 
    0, 51, 0, 100, 0, 
    91, 0, 95, 0, 93, 
    96, 73, 96, 107, 111, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 273,
    'CO_f + *_f -> CO_f + *_f(<-)': 303,
    'CO_g + *_f -> CO_f(->)': 5000090,
    'CO_g + *_f -> CO_f(<-)': 4998905,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 143,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 286,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 273,
    'CO_f + *_f -> CO_f + *_f(<-)': 303,
    'CO_g + *_f -> CO_f(->)': 5000090,
    'CO_g + *_f -> CO_f(<-)': 4998905,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 143,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 286,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00311800645839,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00346064453074,
    'CO_g + *_f -> CO_f(->)': 57.1073733059,
    'CO_g + *_f -> CO_f(<-)': 57.093839102,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0016332414782,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0032664829564,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

