# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Wed Jan 23 15:03:08 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    199781, 0, 200192, 0, 99813, 
    0, 100314, 0, 57694, 0, 
    58238, 0, 48207, 0, 47002, 
    0, 48075, 0, 46533, 0, 
    47135, 0, 47016, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 
]

reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 399900,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 399973,
    'CO_g + *_b -> CO_b(<-)': 0,
    'O2_g + 2*_b -> 2O_b(->)': 200127,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 399900,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0,
    'CO_g + *_b -> CO_b(->)': 399973,
    'CO_g + *_b -> CO_b(<-)': 0,
    'O2_g + 2*_b -> 2O_b(->)': 200127,
    'O2_g + 2*_b -> 2O_b(<-)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0,
}

reaction_rates = {
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)': 4876520.55344,
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)': 0.0,
    'CO_g + *_b -> CO_b(->)': 4877410.74099,
    'CO_g + *_b -> CO_b(<-)': 0.0,
    'O2_g + 2*_b -> 2O_b(->)': 2440418.67667,
    'O2_g + 2*_b -> 2O_b(<-)': 0.0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)': 0.0,
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)': 0.0,
}

