# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sat Jan  5 19:48:50 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    4999462, 4997262, 226, 0, 219, 
    0, 207, 0, 444, 0, 
    430, 0, 430, 0, 215, 
    214, 222, 208, 220, 241, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 657,
    'CO_f + *_f -> CO_f + *_f(<-)': 663,
    'CO_g + *_f -> CO_f(->)': 4999462,
    'CO_g + *_f -> CO_f(<-)': 4997262,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 652,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 1304,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 657,
    'CO_f + *_f -> CO_f + *_f(<-)': 663,
    'CO_g + *_f -> CO_f(->)': 4999462,
    'CO_g + *_f -> CO_f(<-)': 4997262,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 652,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 1304,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00750314875478,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00757167066122,
    'CO_g + *_f -> CO_f(->)': 57.095444566,
    'CO_g + *_f -> CO_f(<-)': 57.070319867,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00744604716608,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0148920943322,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

