# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 23:29:30 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14994812, 14990561, 532, 0, 556, 
    0, 588, 0, 1106, 0, 
    1167, 0, 1079, 0, 1612, 
    1613, 1645, 1599, 1552, 1578, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4809,
    'CO_f + *_f -> CO_f + *_f(<-)': 4790,
    'CO_g + *_f -> CO_f(->)': 14994812,
    'CO_g + *_f -> CO_f(<-)': 14990561,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 1676,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 3352,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4809,
    'CO_f + *_f -> CO_f + *_f(<-)': 4790,
    'CO_g + *_f -> CO_f(->)': 14994812,
    'CO_g + *_f -> CO_f(<-)': 14990561,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 1676,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 3352,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0182671603812,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0181949881942,
    'CO_g + *_f -> CO_f(->)': 56.9583355563,
    'CO_g + *_f -> CO_f(<-)': 56.9421879791,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00636634659991,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0127326931998,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

