# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 23:29:30 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14994532, 14989113, 807, 0, 717, 
    0, 736, 0, 1471, 0, 
    1533, 0, 1516, 0, 1574, 
    1626, 1638, 1605, 1565, 1567, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4777,
    'CO_f + *_f -> CO_f + *_f(<-)': 4798,
    'CO_g + *_f -> CO_f(->)': 14994532,
    'CO_g + *_f -> CO_f(<-)': 14989113,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 2260,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 4520,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4777,
    'CO_f + *_f -> CO_f + *_f(<-)': 4798,
    'CO_g + *_f -> CO_f(->)': 14994532,
    'CO_g + *_f -> CO_f(<-)': 14989113,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 2260,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 4520,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0181476658547,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0182274441638,
    'CO_g + *_f -> CO_f(->)': 56.9637338043,
    'CO_g + *_f -> CO_f(<-)': 56.9431472016,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0085856656545,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.017171331309,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

