# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Fri Jan  4 21:14:07 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    3080620, 3078116, 276, 0, 275, 
    0, 252, 0, 573, 0, 
    501, 0, 532, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 
]

reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 3080620,
    'CO_g + *_f -> CO_f(<-)': 3078116,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 803,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 1606,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 3080620,
    'CO_g + *_f -> CO_f(<-)': 3078116,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 803,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 1606,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_g + *_f -> CO_f(->)': 57.0485007237,
    'CO_g + *_f -> CO_f(<-)': 57.0021303678,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0148703657319,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0297407314639,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

