# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 00:24:12 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    4999108, 4996169, 345, 0, 343, 
    0, 333, 0, 715, 0, 
    667, 0, 660, 0, 271, 
    284, 279, 272, 251, 303, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 801,
    'CO_f + *_f -> CO_f + *_f(<-)': 859,
    'CO_g + *_f -> CO_f(->)': 4999108,
    'CO_g + *_f -> CO_f(<-)': 4996169,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 1021,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 2042,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 801,
    'CO_f + *_f -> CO_f + *_f(<-)': 859,
    'CO_g + *_f -> CO_f(->)': 4999108,
    'CO_g + *_f -> CO_f(<-)': 4996169,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 1021,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 2042,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.00914530854454,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.00980751565513,
    'CO_g + *_f -> CO_f(->)': 57.0766355899,
    'CO_g + *_f -> CO_f(<-)': 57.0430799571,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0116571286192,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0233142572384,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

