# This file was automatically generated by scaks (https://github.com/PytLab/scaks).
# Version 0.1.0
# Date: Sun Apr 28 15:03:24 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
tofs = []
processes = [
    'CO_g + *_b -> CO_b(->)', 
    'CO_g + *_b -> CO_b(<-)', 
    'CO_g + *_b -> CO_b(->)', 
    'CO_g + *_b -> CO_b(<-)', 
    'O2_g + 2*_b -> 2O_b(->)', 
    'O2_g + 2*_b -> 2O_b(<-)', 
    'O2_g + 2*_b -> 2O_b(->)', 
    'O2_g + 2*_b -> 2O_b(<-)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(->)', 
    'CO_b + O_b <-> CO-O_2b -> CO2_g + 2*_b(<-)', 
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)', 
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)', 
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(->)', 
    'O_b + *_t <-> O_t + *_b -> O_b + *_t(<-)', 
]

