# This file was automatically generated by scaks (https://github.com/PytLab/scaks).
# Version 0.1.0
# Date: Sat Oct 26 11:35:32 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    180143, 180037, 106, 0, 319699, 
    319593, 105, 0, 105, 0, 
    106, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 105, 0, 
]

reaction_occurencies = {
    'CH3_c + *_b <-> CH3-_c + *_b -> CH3_b + *_c(->)': 106,
    'CH3_c + *_b <-> CH3-_c + *_b -> CH3_b + *_c(<-)': 0,
    'CH4_g + *_a + *_c <-> CH3-H_c + *_a -> CH3_c + H_a(->)': 180143,
    'CH4_g + *_a + *_c <-> CH3-H_c + *_a -> CH3_c + H_a(<-)': 180037,
    'CHO_c + *_b <-> CHO-_c + *_b -> CHO_b + *_c(->)': 0,
    'CHO_c + *_b <-> CHO-_c + *_b -> CHO_b + *_c(<-)': 0,
    'O2_c + CH3_b <-> OO-H_c + CH2_b -> OOH_c + CH2_b(->)': 105,
    'O2_c + CH3_b <-> OO-H_c + CH2_b -> OOH_c + CH2_b(<-)': 0,
    'O2_c + CHO_b + O_v <-> OO-H_c + CO_b + O_v -> OOH_c + CO2_g + *_b + *_v(->)': 0,
    'O2_c + CHO_b + O_v <-> OO-H_c + CO_b + O_v -> OOH_c + CO2_g + *_b + *_v(<-)': 0,
    'O2_g + *_c + CH3_b -> O2_c + CH3_b(->)': 319699,
    'O2_g + *_c + CH3_b -> O2_c + CH3_b(<-)': 319593,
    'O2_g + CHO_b + *_c -> O2_c + CHO_b(->)': 0,
    'O2_g + CHO_b + *_c -> O2_c + CHO_b(<-)': 0,
    'OCH2_b + *_c <-> OCH2-_b + *_c -> *_b + OCH2_c(->)': 106,
    'OCH2_b + *_c <-> OCH2-_b + *_c -> *_b + OCH2_c(<-)': 1,
    'OCH2_c + *_a <-> OCH-H_c + *_a -> CHO_c + H_a(->)': 0,
    'OCH2_c + *_a <-> OCH-H_c + *_a -> CHO_c + H_a(<-)': 0,
    'OCH2_c -> *_c + HCHO_g(->)': 105,
    'OCH2_c -> *_c + HCHO_g(<-)': 0,
    'OOH_c + H_a + *_v -> H2O_g + *_c + *_a + O_v(->)': 0,
    'OOH_c + H_a + *_v -> H2O_g + *_c + *_a + O_v(<-)': 0,
    'OOH_c + H_a + CH2_b <-> OOH-H_c + *_a + CH2_b -> H2O_g + OCH2_b + *_a + *_c(->)': 105,
    'OOH_c + H_a + CH2_b <-> OOH-H_c + *_a + CH2_b -> H2O_g + OCH2_b + *_a + *_c(<-)': 0,
}

steady_reaction_occurencies = {
    'CH3_c + *_b <-> CH3-_c + *_b -> CH3_b + *_c(->)': 106,
    'CH3_c + *_b <-> CH3-_c + *_b -> CH3_b + *_c(<-)': 0,
    'CH4_g + *_a + *_c <-> CH3-H_c + *_a -> CH3_c + H_a(->)': 180143,
    'CH4_g + *_a + *_c <-> CH3-H_c + *_a -> CH3_c + H_a(<-)': 180037,
    'CHO_c + *_b <-> CHO-_c + *_b -> CHO_b + *_c(->)': 0,
    'CHO_c + *_b <-> CHO-_c + *_b -> CHO_b + *_c(<-)': 0,
    'O2_c + CH3_b <-> OO-H_c + CH2_b -> OOH_c + CH2_b(->)': 105,
    'O2_c + CH3_b <-> OO-H_c + CH2_b -> OOH_c + CH2_b(<-)': 0,
    'O2_c + CHO_b + O_v <-> OO-H_c + CO_b + O_v -> OOH_c + CO2_g + *_b + *_v(->)': 0,
    'O2_c + CHO_b + O_v <-> OO-H_c + CO_b + O_v -> OOH_c + CO2_g + *_b + *_v(<-)': 0,
    'O2_g + *_c + CH3_b -> O2_c + CH3_b(->)': 319699,
    'O2_g + *_c + CH3_b -> O2_c + CH3_b(<-)': 319593,
    'O2_g + CHO_b + *_c -> O2_c + CHO_b(->)': 0,
    'O2_g + CHO_b + *_c -> O2_c + CHO_b(<-)': 0,
    'OCH2_b + *_c <-> OCH2-_b + *_c -> *_b + OCH2_c(->)': 106,
    'OCH2_b + *_c <-> OCH2-_b + *_c -> *_b + OCH2_c(<-)': 1,
    'OCH2_c + *_a <-> OCH-H_c + *_a -> CHO_c + H_a(->)': 0,
    'OCH2_c + *_a <-> OCH-H_c + *_a -> CHO_c + H_a(<-)': 0,
    'OCH2_c -> *_c + HCHO_g(->)': 105,
    'OCH2_c -> *_c + HCHO_g(<-)': 0,
    'OOH_c + H_a + *_v -> H2O_g + *_c + *_a + O_v(->)': 0,
    'OOH_c + H_a + *_v -> H2O_g + *_c + *_a + O_v(<-)': 0,
    'OOH_c + H_a + CH2_b <-> OOH-H_c + *_a + CH2_b -> H2O_g + OCH2_b + *_a + *_c(->)': 105,
    'OOH_c + H_a + CH2_b <-> OOH-H_c + *_a + CH2_b -> H2O_g + OCH2_b + *_a + *_c(<-)': 0,
}

reaction_rates = {
    'CH3_c + *_b <-> CH3-_c + *_b -> CH3_b + *_c(->)': 4.023438910694107e-06,
    'CH3_c + *_b <-> CH3-_c + *_b -> CH3_b + *_c(<-)': 0.0,
    'CH4_g + *_a + *_c <-> CH3-H_c + *_a -> CH3_c + H_a(->)': 0.006837682600841212,
    'CH4_g + *_a + *_c <-> CH3-H_c + *_a -> CH3_c + H_a(<-)': 0.006833659161930518,
    'CHO_c + *_b <-> CHO-_c + *_b -> CHO_b + *_c(->)': 0.0,
    'CHO_c + *_b <-> CHO-_c + *_b -> CHO_b + *_c(<-)': 0.0,
    'O2_c + CH3_b <-> OO-H_c + CH2_b -> OOH_c + CH2_b(->)': 3.9854819398385025e-06,
    'O2_c + CH3_b <-> OO-H_c + CH2_b -> OOH_c + CH2_b(<-)': 0.0,
    'O2_c + CHO_b + O_v <-> OO-H_c + CO_b + O_v -> OOH_c + CO2_g + *_b + *_v(->)': 0.0,
    'O2_c + CHO_b + O_v <-> OO-H_c + CO_b + O_v -> OOH_c + CO2_g + *_b + *_v(<-)': 0.0,
    'O2_g + *_c + CH3_b -> O2_c + CH3_b(->)': 0.012134805625565993,
    'O2_g + *_c + CH3_b -> O2_c + CH3_b(<-)': 0.0121307821866553,
    'O2_g + CHO_b + *_c -> O2_c + CHO_b(->)': 0.0,
    'O2_g + CHO_b + *_c -> O2_c + CHO_b(<-)': 0.0,
    'OCH2_b + *_c <-> OCH2-_b + *_c -> *_b + OCH2_c(->)': 4.023438910694107e-06,
    'OCH2_b + *_c <-> OCH2-_b + *_c -> *_b + OCH2_c(<-)': 3.7956970855604786e-08,
    'OCH2_c + *_a <-> OCH-H_c + *_a -> CHO_c + H_a(->)': 0.0,
    'OCH2_c + *_a <-> OCH-H_c + *_a -> CHO_c + H_a(<-)': 0.0,
    'OCH2_c -> *_c + HCHO_g(->)': 3.9854819398385025e-06,
    'OCH2_c -> *_c + HCHO_g(<-)': 0.0,
    'OOH_c + H_a + *_v -> H2O_g + *_c + *_a + O_v(->)': 0.0,
    'OOH_c + H_a + *_v -> H2O_g + *_c + *_a + O_v(<-)': 0.0,
    'OOH_c + H_a + CH2_b <-> OOH-H_c + *_a + CH2_b -> H2O_g + OCH2_b + *_a + *_c(->)': 3.9854819398385025e-06,
    'OOH_c + H_a + CH2_b <-> OOH-H_c + *_a + CH2_b -> H2O_g + OCH2_b + *_a + *_c(<-)': 0.0,
}

