# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Fri Jan  4 14:33:06 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    5413, 5438, 45031, 44085, 2, 
    0, 1, 0, 0, 0, 
    4, 0, 4, 0, 0, 
    0, 5, 0, 6, 0, 
    5, 0, 1, 0, 5, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 
    0, 0, 
]

reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 45031,
    'CO_g + *_f -> CO_f(<-)': 44085,
    'CO_g + *_h -> CO_h(->)': 5413,
    'CO_g + *_h -> CO_h(<-)': 5438,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 3,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 8,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0,
    'O_f + *_h -> O_h + *_f(->)': 0,
    'O_f + *_h -> O_h + *_f(<-)': 0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 6,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 16,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_g + *_f -> CO_f(->)': 45031,
    'CO_g + *_f -> CO_f(<-)': 44085,
    'CO_g + *_h -> CO_h(->)': 5413,
    'CO_g + *_h -> CO_h(<-)': 5438,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 3,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 8,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0,
    'O_f + *_h -> O_h + *_f(->)': 0,
    'O_f + *_h -> O_h + *_f(<-)': 0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 6,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 16,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0,
}

reaction_rates = {
    'CO_g + *_f -> CO_f(->)': 53.5794404625,
    'CO_g + *_f -> CO_f(<-)': 52.4538569605,
    'CO_g + *_h -> CO_h(->)': 6.4405745203,
    'CO_g + *_h -> CO_h(<-)': 6.47032038451,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.00356950370606,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(->)': 0.00951867654949,
    'O2_g + 2*_h <-> O-O_2h -> 2O_h(<-)': 0.0,
    'O_f + *_h -> O_h + *_f(->)': 0.0,
    'O_f + *_h -> O_h + *_f(<-)': 0.0,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(->)': 0.00713900741211,
    'O_f + CO_h <-> O-CO_h + *_f -> CO2_g + *_h + *_f(<-)': 0.0,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(->)': 0.019037353099,
    'O_h + CO_f <-> O-CO_f + *_h -> CO2_g + *_h + *_f(<-)': 0.0,
}

