# This file was automatically generated by Kynetix (https://github.com/PytLab/Kynetix).
# Version 1.0.0
# Date: Sun Jan  6 18:23:14 2019 
#
# Do not make changes to this file unless you know what you are doing

times = []
picked_indices = []
process_occurencies = []
process_occurencies = [
    14991331, 14973118, 2917, 0, 2879, 
    0, 2861, 0, 5797, 0, 
    5695, 0, 5822, 0, 1557, 
    1662, 1646, 1558, 1588, 1569, 
    0, 0, 0, 0, 0, 
    0, 
]

reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4791,
    'CO_f + *_f -> CO_f + *_f(<-)': 4789,
    'CO_g + *_f -> CO_f(->)': 14991331,
    'CO_g + *_f -> CO_f(<-)': 14973118,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 8657,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 17314,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

steady_reaction_occurencies = {
    'CO_f + *_f -> CO_f + *_f(->)': 4791,
    'CO_f + *_f -> CO_f + *_f(<-)': 4789,
    'CO_g + *_f -> CO_f(->)': 14991331,
    'CO_g + *_f -> CO_f(<-)': 14973118,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 8657,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0,
    'O_f + *_f -> O_f + *_f(->)': 0,
    'O_f + *_f -> O_f + *_f(<-)': 0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 17314,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0,
}

reaction_rates = {
    'CO_f + *_f -> CO_f + *_f(->)': 0.0182210908383,
    'CO_f + *_f -> CO_f + *_f(<-)': 0.0182134844551,
    'CO_g + *_f -> CO_f(->)': 57.0149037649,
    'CO_g + *_f -> CO_f(<-)': 56.9456362368,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(->)': 0.0329242294692,
    'O2_g + 2*_f <-> O-O_2f -> 2O_f(<-)': 0.0,
    'O_f + *_f -> O_f + *_f(->)': 0.0,
    'O_f + *_f -> O_f + *_f(<-)': 0.0,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(->)': 0.0658484589384,
    'O_f + CO_f <-> O-CO_f + *_f -> CO2_g + *_f + *_f(<-)': 0.0,
}

